# Generated by Django 5.1.10 on 2025-11-15 11:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_course_program'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pomodoro_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('focus_duration', models.IntegerField(default=25, help_text='Focus session duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('short_break', models.IntegerField(default=5, help_text='Short break duration in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('long_break', models.IntegerField(default=15, help_text='Long break duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('sessions_until_long_break', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('auto_start_breaks', models.BooleanField(default=False)),
                ('auto_start_pomodoros', models.BooleanField(default=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pomodoro Settings',
                'verbose_name_plural': 'Pomodoro Settings',
                'db_table': 'planner_pomodoro_settings',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=255)),
                ('instructor', models.CharField(blank=True, max_length=255)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('once', 'One Time')], default='weekly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'db_table': 'planner_class_schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('semester', 'Semester')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('personal', 'Personal'), ('health', 'Health'), ('career', 'Career')], default='academic', max_length=20)),
                ('target_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(help_text='e.g., hours, tasks, pages', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'db_table': 'planner_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_created', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('study_time', models.IntegerField(default=0)),
                ('pomodoro_sessions', models.IntegerField(default=0)),
                ('break_time', models.IntegerField(default=0)),
                ('productivity_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('focus_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Statistics',
                'verbose_name_plural': 'Study Statistics',
                'db_table': 'planner_study_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_code', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emoji', models.CharField(default='📝', max_length=10)),
                ('color_gradient_start', models.CharField(default='#667eea', max_length=7)),
                ('color_gradient_end', models.CharField(default='#764ba2', max_length=7)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual time spent in minutes', null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_tasks', to='academics.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'planner_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='planner.task')),
            ],
            options={
                'db_table': 'planner_subtasks',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Session duration in minutes')),
                ('completed', models.BooleanField(default=False)),
                ('was_interrupted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='planner.task')),
            ],
            options={
                'db_table': 'planner_pomodoro_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlannerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('task_reminder', 'Task Reminder'), ('class_reminder', 'Class Reminder'), ('break_reminder', 'Break Reminder'), ('goal_progress', 'Goal Progress'), ('achievement', 'Achievement')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('class_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='planner.classschedule')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='planner.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='planner.task')),
            ],
            options={
                'verbose_name': 'Planner Notification',
                'verbose_name_plural': 'Planner Notifications',
                'db_table': 'planner_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='planner/attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.task')),
            ],
            options={
                'db_table': 'planner_task_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('study_time', 'Study Time Recommendation'), ('priority', 'Priority Suggestion'), ('productivity', 'Productivity Tip'), ('break', 'Break Reminder')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('icon', models.CharField(default='bulb', max_length=50)),
                ('color', models.CharField(default='#F59E0B', max_length=7)),
                ('priority', models.IntegerField(default=0)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_acted_upon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Suggestion',
                'verbose_name_plural': 'AI Suggestions',
                'db_table': 'planner_ai_suggestions',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_dismissed', 'expires_at'], name='planner_ai__user_id_f92b8e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['user', 'day_of_week', 'is_active'], name='planner_cla_user_id_f0f349_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'goal_type', 'completed'], name='planner_goa_user_id_fc3175_idx'),
        ),
        migrations.AddIndex(
            model_name='studystatistics',
            index=models.Index(fields=['user', 'date'], name='planner_stu_user_id_176abc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studystatistics',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'completed', 'due_date'], name='planner_tas_user_id_8bbfff_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'priority'], name='planner_tas_user_id_1df900_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='planner_tas_user_id_5e71ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'start_time'], name='planner_pom_user_id_9380aa_idx'),
        ),
        migrations.AddIndex(
            model_name='plannernotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='planner_not_user_id_8bf3ce_idx'),
        ),
    ]
