# Generated by Django 5.2.8 on 2025-12-11 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentUpdateReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.CharField(help_text="The ID of the update (e.g., 'event-{uuid}', 'helpdesk-{tracking_id}')", max_length=255)),
                ('update_type', models.CharField(help_text='Type of update (task_created, event_created, etc.)', max_length=50)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='User deleted this notification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent Update Read Status',
                'verbose_name_plural': 'Recent Update Read Statuses',
                'db_table': 'recent_update_read_status',
                'indexes': [models.Index(fields=['user', 'is_deleted'], name='recent_upda_user_id_a4ca19_idx'), models.Index(fields=['update_id'], name='recent_upda_update__ae4adc_idx'), models.Index(fields=['read_at'], name='recent_upda_read_at_ee7e64_idx')],
                'unique_together': {('user', 'update_id')},
            },
        ),
    ]
