# Generated by Django 5.1.10 on 2025-11-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='file_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide file URL (Google Drive, Dropbox, etc.) instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='planner/attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
