# Generated by Django 5.2.8 on 2025-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_taskattachment_file_url_alter_taskattachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannernotification',
            name='class_schedule',
        ),
        migrations.AlterField(
            model_name='plannernotification',
            name='notification_type',
            field=models.CharField(choices=[('task_reminder', 'Task Reminder'), ('break_reminder', 'Break Reminder'), ('goal_progress', 'Goal Progress'), ('achievement', 'Achievement')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
    ]
