# Generated by Django 5.2.2 on 2025-12-30 05:12

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_plannernotification_class_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='planner/attachments/%Y/%m/'),
        ),
    ]
