# Generated by Django 5.1.10 on 2025-11-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0003_alter_executive_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL (Google Drive, Dropbox, etc.) instead of uploading', null=True),
        ),
    ]
