# Generated by Django 5.2.8 on 2025-11-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0009_alter_appointeepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['position__priority', '-office_from'], 'verbose_name': 'Executive', 'verbose_name_plural': 'Executives'},
        ),
        migrations.AlterModelOptions(
            name='executiveposition',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='executiveposition',
            name='priority',
            field=models.IntegerField(default=999, help_text='Lower value = higher display priority (1 = top).'),
        ),
    ]
