# Generated by Django 5.2.8 on 2025-11-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0012_alter_executive_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Mx', 'Mx'), ('Other', 'Other')], help_text='Optional title (e.g., Mr, Ms, Dr)', max_length=20, null=True),
        ),
    ]
