# Generated by Django 5.2.8 on 2025-11-27 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0014_executive_unique_position_office_year_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionauditlog',
            name='target_committee',
            field=models.ForeignKey(blank=True, help_text='Committee affected by the permission change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to='executives.committee'),
        ),
        migrations.AlterField(
            model_name='permissionauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User who received the permission change (kept for audit trail even if user deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
