# Generated by Django 5.1.10 on 2025-11-12 10:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskCategory',
            fields=[
                ('id', models.CharField(choices=[('academic', 'Academic Help'), ('technical', 'Technical Support'), ('society', 'Society & Events'), ('codequest', 'CodeQuest Support'), ('career', 'Career & Internships'), ('general', 'General Help')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HelpDesk Category',
                'verbose_name_plural': 'HelpDesk Categories',
                'db_table': 'helpdesk_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpDeskRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(5000)])),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('response_count', models.IntegerField(default=0)),
                ('helpful_response_count', models.IntegerField(default=0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_requests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='helpdesk.helpdeskcategory')),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
                'db_table': 'helpdesk_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='helpdesk.helpdeskrequest')),
            ],
            options={
                'db_table': 'helpdesk_code_snippets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpDeskResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(10000)])),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('follow_up_count', models.IntegerField(default=0)),
                ('is_marked_helpful', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_helpful_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_responses', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='helpdesk.helpdeskrequest')),
            ],
            options={
                'verbose_name': 'Help Response',
                'verbose_name_plural': 'Help Responses',
                'db_table': 'helpdesk_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpDeskNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_response', 'New Response'), ('response_marked_helpful', 'Response Marked Helpful'), ('response_upvoted', 'Response Upvoted'), ('request_resolved', 'Request Resolved'), ('follow_up', 'Follow-up Question')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.helpdeskrequest')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.helpdeskresponse')),
            ],
            options={
                'db_table': 'helpdesk_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam or Advertising'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate'), ('off_topic', 'Off Topic'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_helpdesk_reports', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='helpdesk.helpdeskrequest')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='helpdesk.helpdeskresponse')),
            ],
            options={
                'db_table': 'helpdesk_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='helpdesk.helpdeskrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'helpdesk_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='helpdesk/requests/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='helpdesk/requests/thumbnails/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='helpdesk.helpdeskrequest')),
            ],
            options={
                'db_table': 'helpdesk_request_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='helpdesk.helpdeskrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'helpdesk_views',
            },
        ),
        migrations.CreateModel(
            name='ResponseCodeSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='helpdesk.helpdeskresponse')),
            ],
            options={
                'db_table': 'helpdesk_response_code_snippets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='helpdesk.helpdeskresponse')),
            ],
            options={
                'db_table': 'helpdesk_response_links',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='helpdesk.helpdeskresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'helpdesk_votes',
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('requests_created', models.IntegerField(default=0)),
                ('requests_resolved', models.IntegerField(default=0)),
                ('responses_posted', models.IntegerField(default=0)),
                ('helpful_responses', models.IntegerField(default=0)),
                ('upvotes_received', models.IntegerField(default=0)),
                ('downvotes_received', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'helpdesk_user_reputation',
            },
        ),
        migrations.AddIndex(
            model_name='helpdeskrequest',
            index=models.Index(fields=['-created_at'], name='helpdesk_re_created_d3c17e_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskrequest',
            index=models.Index(fields=['category', '-created_at'], name='helpdesk_re_categor_922732_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskrequest',
            index=models.Index(fields=['priority', '-created_at'], name='helpdesk_re_priorit_dd8c78_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskrequest',
            index=models.Index(fields=['status', '-created_at'], name='helpdesk_re_status_bec4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskrequest',
            index=models.Index(fields=['author', '-created_at'], name='helpdesk_re_author__207e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskresponse',
            index=models.Index(fields=['request', '-created_at'], name='helpdesk_re_request_3dad9d_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskresponse',
            index=models.Index(fields=['request', '-upvotes'], name='helpdesk_re_request_bca738_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskresponse',
            index=models.Index(fields=['author', '-created_at'], name='helpdesk_re_author__4a65b8_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdesknotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='helpdesk_no_user_id_789b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['status', '-created_at'], name='helpdesk_re_status_ed5efe_idx'),
        ),
        migrations.AddIndex(
            model_name='requestbookmark',
            index=models.Index(fields=['user', '-created_at'], name='helpdesk_bo_user_id_d3d6bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestbookmark',
            unique_together={('request', 'user')},
        ),
        migrations.AddIndex(
            model_name='requestview',
            index=models.Index(fields=['request', '-viewed_at'], name='helpdesk_vi_request_7c03d2_idx'),
        ),
        migrations.AddIndex(
            model_name='requestview',
            index=models.Index(fields=['user', '-viewed_at'], name='helpdesk_vi_user_id_534b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='responsevote',
            index=models.Index(fields=['response', 'vote_type'], name='helpdesk_vo_respons_dddbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='responsevote',
            index=models.Index(fields=['user', '-created_at'], name='helpdesk_vo_user_id_47957e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responsevote',
            unique_together={('response', 'user')},
        ),
    ]
