# Generated by Django 5.1.10 on 2025-11-13 07:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(2000)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_replies', to=settings.AUTH_USER_MODEL)),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='helpdesk.responsereply')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='helpdesk.helpdeskresponse')),
            ],
            options={
                'verbose_name': 'Response Reply',
                'verbose_name_plural': 'Response Replies',
                'db_table': 'helpdesk_response_replies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['response', 'created_at'], name='helpdesk_re_respons_3ad3c8_idx'), models.Index(fields=['author', '-created_at'], name='helpdesk_re_author__1c99d7_idx')],
            },
        ),
    ]
