# Generated by Django 5.1.10 on 2025-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_responsereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='requestimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide thumbnail URL instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='requestimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='helpdesk/requests/%Y/%m/'),
        ),
    ]
