# Generated by Django 5.2.2 on 2025-12-30 05:12

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_requestimage_image_url_requestimage_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='helpdesk/requests/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='requestimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='helpdesk/requests/thumbnails/%Y/%m/'),
        ),
    ]
