# Generated by Django 5.2.8 on 2025-12-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_populate_initial_data'),
        ('payments', '0005_add_variant_selections_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorpayment',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL to redirect after payment', null=True),
        ),
        migrations.AddField(
            model_name='mentorpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Linked transaction from payments system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_payments', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='mentorpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mentorpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='mentorpayment',
            name='transaction_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction reference for quick lookup', max_length=100),
        ),
        migrations.AddIndex(
            model_name='mentorpayment',
            index=models.Index(fields=['status', 'created_at'], name='mentorship__status_e872d2_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorpayment',
            index=models.Index(fields=['mentor', 'status'], name='mentorship__mentor__bbf83a_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorpayment',
            index=models.Index(fields=['mentee', 'status'], name='mentorship__mentee__c5c3cd_idx'),
        ),
    ]
