# Generated by Django 5.1.10 on 2025-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_level_remove_project_student_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image2_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image 2 URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image3_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image 3 URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main project image/screenshot', null=True, upload_to='projects/'),
        ),
    ]
