# Generated by Django 5.2.8 on 2025-12-05 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0015_alter_permissionauditlog_target_committee_and_more'),
        ('projects', '0003_project_image2_url_project_image3_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the project was approved', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Executive who approved this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to='executives.executive'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Project must be approved by an executive'),
        ),
    ]
