# Generated by Django 5.2.8 on 2025-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_approved_at_project_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.CharField(help_text='Year project was completed', max_length=10),
        ),
    ]
