# Generated by Django 5.2.2 on 2025-12-30 05:12

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_level_to_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main project image/screenshot', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, help_text='Additional image (optional)', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, help_text='Additional image (optional)', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='projects/'),
        ),
    ]
