# Generated by Django 5.2.8 on 2025-12-30 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_image_alter_project_image2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='is_submitter',
            field=models.BooleanField(default=False, help_text='Is this the person who submitted the project?'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (optional)', max_length=20),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Link to registered user account (if they have one)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
