# Generated by Django 5.2.8 on 2025-12-03 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template identifier (e.g., 'class_reminder')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Notification title (supports {variable} placeholders)', max_length=100)),
                ('body', models.TextField(help_text='Notification body (supports {variable} placeholders)')),
                ('data', models.JSONField(blank=True, default=dict, help_text="Additional data payload as JSON (e.g., {'screen': 'ClassSchedule', 'scheduleId': '{schedule_id}'})")),
                ('sound', models.CharField(default='default', help_text='Notification sound', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('default', 'Default'), ('low', 'Low')], default='default', max_length=10)),
                ('badge', models.IntegerField(default=1, help_text='Badge count for iOS')),
                ('category', models.CharField(blank=True, help_text='Notification category', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Push Notification Template',
                'verbose_name_plural': 'Push Notification Templates',
                'db_table': 'push_notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('class_reminders', models.BooleanField(default=True)),
                ('exam_reminders', models.BooleanField(default=True)),
                ('event_notifications', models.BooleanField(default=True)),
                ('deadline_reminders', models.BooleanField(default=True)),
                ('general_announcements', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='e.g., 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='e.g., 07:00', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this trigger', max_length=100)),
                ('trigger_type', models.CharField(choices=[('class_schedule', 'Class Schedule'), ('exam_schedule', 'Exam Schedule'), ('event', 'Event'), ('deadline', 'Deadline'), ('custom', 'Custom')], max_length=50)),
                ('offset_value', models.IntegerField(help_text='Time before event (e.g., 1, 24)')),
                ('offset_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='hours', max_length=10)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="Additional conditions (e.g., {'day_of_week': [1,2,3], 'program': 'CS'})")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.pushnotificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification Trigger',
                'verbose_name_plural': 'Notification Triggers',
                'db_table': 'notification_triggers',
            },
        ),
        migrations.CreateModel(
            name='PushNotificationDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_token', models.TextField(help_text='Expo push token or FCM token', unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('device_name', models.CharField(blank=True, help_text='Device name or model', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device should receive notifications')),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification Device',
                'verbose_name_plural': 'Push Notification Devices',
                'db_table': 'push_notification_devices',
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_notifi_user_id_aac935_idx'), models.Index(fields=['device_token'], name='push_notifi_device__458122_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data payload')),
                ('sound', models.CharField(default='default', max_length=50)),
                ('priority', models.CharField(default='default', max_length=10)),
                ('badge', models.IntegerField(default=1)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send this notification', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('trigger_type', models.CharField(blank=True, help_text="e.g., 'class_schedule', 'exam_schedule', 'manual'", max_length=50, null=True)),
                ('trigger_id', models.CharField(blank=True, help_text='ID of the object that triggered this notification', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.pushnotificationtemplate')),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='push_notifi_user_id_d4b225_idx'), models.Index(fields=['scheduled_at', 'status'], name='push_notifi_schedul_5597c0_idx'), models.Index(fields=['trigger_type', 'trigger_id'], name='push_notifi_trigger_f45880_idx')],
            },
        ),
    ]
