# Generated by Django 5.2.8 on 2025-12-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_recentupdatereadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationdevice',
            name='web_subscription',
            field=models.JSONField(blank=True, help_text='Web Push subscription object containing endpoint, keys (p256dh, auth)', null=True),
        ),
    ]
