# Generated by Django 5.2.8 on 2026-02-03 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarReminderPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_reminders_enabled', models.BooleanField(default=True)),
                ('class_reminder_times', models.JSONField(default=list, help_text='List of minutes before class to send reminders. e.g., [15, 30, 60]')),
                ('exam_reminders_enabled', models.BooleanField(default=True)),
                ('exam_reminder_times', models.JSONField(default=list, help_text='List of minutes before exam to send reminders. e.g., [30, 120, 1440]')),
                ('event_reminders_enabled', models.BooleanField(default=True)),
                ('event_reminder_times', models.JSONField(default=list, help_text='List of minutes before event to send reminders. e.g., [60, 1440]')),
                ('push_reminders_enabled', models.BooleanField(default=True, help_text='Send push notifications as reminders (most reliable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_reminder_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Reminder Preference',
                'verbose_name_plural': 'Calendar Reminder Preferences',
            },
        ),
        migrations.CreateModel(
            name='ScheduledCalendarReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('class', 'Class Reminder'), ('exam', 'Exam Reminder'), ('event', 'Event Reminder')], max_length=20)),
                ('reference_model', models.CharField(help_text="Model name e.g., 'ClassSchedule', 'ExaminationSchedule', 'Event'", max_length=50)),
                ('reference_id', models.CharField(help_text='ID of the referenced object', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('event_datetime', models.DateTimeField(help_text='When the actual event starts')),
                ('remind_at', models.DateTimeField(db_index=True, help_text='When to send this reminder')),
                ('minutes_before', models.PositiveIntegerField(help_text='How many minutes before the event this reminder is for')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('unique_key', models.CharField(help_text='Unique identifier to prevent duplicate reminders', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Calendar Reminder',
                'verbose_name_plural': 'Scheduled Calendar Reminders',
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['status', 'remind_at'], name='calendar_sy_status_ed7b63_idx'), models.Index(fields=['user', 'status'], name='calendar_sy_user_id_525c57_idx'), models.Index(fields=['reminder_type', 'status'], name='calendar_sy_reminde_792f46_idx')],
            },
        ),
    ]
