# Generated by Django 5.2.8 on 2025-11-20 19:30

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'Level 200 Course Rep Elections 2024/2025'", max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(help_text='Full description of the voting event')),
                ('event_type', models.CharField(choices=[('election', 'Election'), ('awards', 'Awards Voting'), ('poll', 'Opinion Poll'), ('referendum', 'Referendum')], default='election', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('voting_open', 'Voting Open'), ('voting_closed', 'Voting Closed'), ('results_published', 'Results Published'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Public - All students can see'), ('level', 'Level Specific - Only specific levels'), ('program', 'Program Specific - Only specific programs'), ('private', 'Private - Invited users only')], default='public', max_length=20)),
                ('banner_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('banner_image_url', models.URLField(blank=True, help_text='Alternative: Provide image URL', null=True)),
                ('registration_start_date', models.DateTimeField(help_text='When candidates can register')),
                ('registration_end_date', models.DateTimeField(help_text='Last day for candidate registration')),
                ('voting_start_date', models.DateTimeField(help_text='When voting opens')),
                ('voting_end_date', models.DateTimeField(help_text='When voting closes')),
                ('eligible_levels', models.JSONField(blank=True, default=list, help_text='List of levels that can vote: [100, 200, 300, 400]')),
                ('eligible_programs', models.JSONField(blank=True, default=list, help_text="List of programs: ['CS', 'IT', 'Data Science']")),
                ('requires_payment', models.BooleanField(default=False, help_text='Does voting require payment?')),
                ('voting_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for voting (if required)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('allow_multiple_votes', models.BooleanField(default=False, help_text='Allow users to vote in multiple categories?')),
                ('show_live_results', models.BooleanField(default=False, help_text='Show results while voting is ongoing?')),
                ('anonymous_voting', models.BooleanField(default=True, help_text='Hide voter identities in results?')),
                ('max_votes_per_category', models.IntegerField(default=1, help_text='Maximum votes per category (1 for single winner)', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_registered_candidates', models.IntegerField(default=0)),
                ('total_eligible_voters', models.IntegerField(default=0)),
                ('total_votes_cast', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voting_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voting Event',
                'verbose_name_plural': 'Voting Events',
                'ordering': ['-voting_start_date'],
            },
        ),
        migrations.CreateModel(
            name='VotingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Best Male Student' or 'Course Rep - CS'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display categories')),
                ('max_votes_allowed', models.IntegerField(default=1, help_text='How many candidates can a voter select in this category?', validators=[django.core.validators.MinValueValidator(1)])),
                ('eligible_levels', models.JSONField(blank=True, default=list, help_text='Override event-level eligibility for this category')),
                ('eligible_programs', models.JSONField(blank=True, default=list, help_text='Override event-level eligibility for this category')),
                ('total_candidates', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='voting.votingevent')),
            ],
            options={
                'verbose_name': 'Voting Category',
                'verbose_name_plural': 'Voting Categories',
                'ordering': ['event', 'display_order', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_id', models.CharField(blank=True, help_text='Student ID or unique identifier', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Candidate biography/manifesto')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('program', models.CharField(blank=True, help_text='CS, IT, etc.', max_length=50)),
                ('level', models.IntegerField(blank=True, help_text='100, 200, 300, 400', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disqualified', 'Disqualified')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about approval/rejection')),
                ('vote_count', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, help_text='Final position/rank', null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_candidates', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.ForeignKey(blank=True, help_text='Link to user account if candidate is a user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for single-category elections', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.votingcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.votingevent')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-vote_count', 'candidate_name'],
                'unique_together': {('event', 'candidate_id')},
            },
        ),
        migrations.CreateModel(
            name='VotingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='voting.votingevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voting Payment',
                'verbose_name_plural': 'Voting Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='VoterEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_eligible', models.BooleanField(default=True)),
                ('eligibility_reason', models.TextField(blank=True, help_text='Why eligible or not eligible')),
                ('has_voted', models.BooleanField(default=False)),
                ('vote_date', models.DateTimeField(blank=True, null=True)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_eligibility', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_voters', to='voting.votingevent')),
            ],
            options={
                'verbose_name': 'Voter Eligibility',
                'verbose_name_plural': 'Voter Eligibilities',
                'indexes': [models.Index(fields=['event', 'is_eligible'], name='voting_vote_event_i_9e14d4_idx'), models.Index(fields=['event', 'has_voted'], name='voting_vote_event_i_7b0ea8_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='voting.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votingcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votingevent')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-vote_date'],
                'indexes': [models.Index(fields=['event', 'candidate'], name='voting_vote_event_i_707b9b_idx'), models.Index(fields=['voter', 'event'], name='voting_vote_voter_i_793f08_idx')],
                'unique_together': {('voter', 'event', 'category')},
            },
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_votes_cast', models.IntegerField(default=0)),
                ('total_eligible_voters', models.IntegerField(default=0)),
                ('voter_turnout_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of eligible voters who voted', max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('detailed_results', models.JSONField(default=dict, help_text='Full breakdown of votes per candidate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='voting.votingcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='voting.votingevent')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_results', to='voting.candidate')),
            ],
            options={
                'verbose_name': 'Voting Result',
                'verbose_name_plural': 'Voting Results',
                'unique_together': {('event', 'category')},
            },
        ),
    ]
