# Generated by Django 5.2.8 on 2025-11-21 04:20

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Voting Payment', 'verbose_name_plural': 'Voting Payments'},
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='authorization_code',
            field=models.CharField(blank=True, help_text='For recurring payments', max_length=100),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='authorization_url',
            field=models.URLField(blank=True, help_text='Paystack payment URL'),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='bank',
            field=models.CharField(blank=True, help_text='Bank used for payment', max_length=100),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='card_type',
            field=models.CharField(blank=True, help_text='Card type if paid with card (Visa, Mastercard, Verve)', max_length=50),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='channel',
            field=models.CharField(blank=True, help_text='Payment channel used (card, mobile_money, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghana Cedis (GHS)'), ('USD', 'US Dollars (USD)'), ('NGN', 'Nigerian Naira (NGN)'), ('ZAR', 'South African Rand (ZAR)'), ('KES', 'Kenyan Shilling (KES)')], default='GHS', help_text='Currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='email',
            field=models.EmailField(blank=True, help_text='Email used for payment', max_length=254),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='gateway_response',
            field=models.CharField(blank=True, help_text='Response from payment gateway', max_length=255),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of payment initiator', null=True),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional payment metadata from Paystack'),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='paystack_access_code',
            field=models.CharField(blank=True, help_text='Paystack access code', max_length=100),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100),
        ),
        migrations.AddField(
            model_name='votingpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='votingpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in main currency unit (e.g., GHS)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='votingpayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When payment was actually completed', null=True),
        ),
        migrations.AlterField(
            model_name='votingpayment',
            name='payment_method',
            field=models.CharField(choices=[('paystack_card', 'Paystack - Card'), ('paystack_mobile_money', 'Paystack - Mobile Money'), ('paystack_bank', 'Paystack - Bank'), ('paystack_ussd', 'Paystack - USSD'), ('paystack_bank_transfer', 'Paystack - Bank Transfer'), ('paystack_qr', 'Paystack - QR Code'), ('manual_cash', 'Manual - Cash'), ('manual_transfer', 'Manual - Bank Transfer'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='votingpayment',
            name='payment_reference',
            field=models.CharField(help_text='Unique payment reference (Paystack or custom)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='votingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('verified', 'Verified'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='votingpayment',
            index=models.Index(fields=['event', 'status'], name='voting_voti_event_i_d73792_idx'),
        ),
        migrations.AddIndex(
            model_name='votingpayment',
            index=models.Index(fields=['user', 'status'], name='voting_voti_user_id_8699be_idx'),
        ),
        migrations.AddIndex(
            model_name='votingpayment',
            index=models.Index(fields=['payment_reference'], name='voting_voti_payment_d3fcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='votingpayment',
            index=models.Index(fields=['paystack_reference'], name='voting_voti_paystac_b9518c_idx'),
        ),
    ]
