# Generated by Django 5.2.8 on 2025-11-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_votingpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingevent',
            name='allow_candidate_self_voting',
            field=models.BooleanField(default=False, help_text='Allow candidates to vote in this event (including for themselves)?'),
        ),
    ]
