# Generated by Django 5.2.8 on 2025-11-22 06:45

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_votingevent_allow_candidate_self_voting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid for these votes', max_digits=10),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_quantity',
            field=models.IntegerField(default=1, help_text='Number of votes purchased (default: 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='allow_multiple_vote_purchase',
            field=models.BooleanField(default=False, help_text='Allow users to buy multiple votes for a candidate?'),
        ),
        migrations.AlterField(
            model_name='votingevent',
            name='voting_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per vote (price per single vote)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['payment_reference'], name='voting_vote_payment_f87e58_idx'),
        ),
    ]
