# Generated by Django 5.2.8 on 2025-12-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_votingevent_title_alter_votingevent_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingevent',
            name='registration_open',
            field=models.BooleanField(default=False, help_text='Master switch: Enable candidate registration. When OFF, registration is closed regardless of dates.'),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='voting_open',
            field=models.BooleanField(default=False, help_text='Master switch: Enable voting. When OFF, voting is closed regardless of dates.'),
        ),
        migrations.AlterField(
            model_name='votingevent',
            name='registration_start_date',
            field=models.DateTimeField(help_text='When candidates can register (only if registration_open is ON)'),
        ),
        migrations.AlterField(
            model_name='votingevent',
            name='voting_start_date',
            field=models.DateTimeField(help_text='When voting opens (only if voting_open is ON)'),
        ),
    ]
