# Generated by Django 5.2.8 on 2025-12-28 09:17

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_vote_device_fingerprint_vote_session_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='The candidate voted for (for election/awards events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='voting.candidate'),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(help_text="The option/choice text (e.g., 'Yes', 'No', 'Strongly Agree', etc.)", max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description or explanation of this option')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Provide image URL', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display options (lower = first)')),
                ('color', models.CharField(blank=True, help_text="Hex color for result visualization (e.g., '#4CAF50')", max_length=7)),
                ('vote_count', models.IntegerField(default=0, help_text='Total votes for this option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='For multi-question polls, link to the question category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='voting.votingcategory')),
                ('event', models.ForeignKey(help_text='The poll/referendum event this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='voting.votingevent')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'ordering': ['event', 'category', 'display_order', 'option_text'],
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='poll_option',
            field=models.ForeignKey(blank=True, help_text='The poll option voted for (for poll/referendum events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='voting.polloption'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['event', 'poll_option'], name='voting_vote_event_i_b56cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['event', 'vote_count'], name='voting_poll_event_i_8cb03e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('event', 'category', 'option_text')},
        ),
    ]
