# Generated by Django 5.2.8 on 2026-01-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='Unique code for applicants to check their status', max_length=12, unique=True),
        ),
    ]
