# Generated by Django 5.2.8 on 2026-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0004_add_seller_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook page name', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram username', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter/X username', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='website',
            field=models.URLField(blank=True, help_text='Your business website', null=True),
        ),
    ]
