# Generated by Django 5.2.8 on 2026-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0011_seed_commission_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_credentials_set',
            field=models.BooleanField(default=False, help_text='Whether seller has set up their login credentials'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Last successful seller portal login', null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this time due to failed attempts', null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for seller portal login', max_length=128),
        ),
        migrations.AddField(
            model_name='seller',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Token for password reset', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, help_text='When the reset token was created', null=True),
        ),
    ]
