# Generated by Django 5.2.8 on 2026-02-06 23:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0012_add_seller_authentication_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacesettings',
            name='payout_processing_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.7'), help_text='Payout processing fee percentage', max_digits=5),
        ),
    ]
