# Generated by Django 5.1.10 on 2025-11-19 11:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='flyer_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide flyer URL (Google Drive, Dropbox, etc.) instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='flyer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
