# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_flyer_url_alter_advertisement_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='Ads/'),
        ),
    ]
