# Generated by Django 5.2.2 on 2025-12-30 05:02

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='flyer',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='Ads/'),
        ),
    ]
