# Generated by Django 5.1.10 on 2025-11-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0002_update_consultant_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codequestparticipant',
            name='deferred_reason',
        ),
    ]
