# Generated by Django 5.1.10 on 2025-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0003_remove_deferred_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestconsultant',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide profile image URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='codequestproject',
            name='app_logo_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide app logo URL instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='codequestconsultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='codequest/consultants/'),
        ),
        migrations.AlterField(
            model_name='codequestproject',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='codequest/logos/'),
        ),
    ]
