# Generated by Django 5.2.8 on 2025-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0004_codequestconsultant_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codequestconsultant',
            name='year_level',
        ),
        migrations.RemoveField(
            model_name='codequestparticipant',
            name='level',
        ),
        migrations.AddField(
            model_name='codequestconsultant',
            name='year',
            field=models.CharField(choices=[('Y3', 'Year 3 (3rd Year)'), ('Y4', 'Year 4 (4th Year)')], default='Y3', help_text='Academic year', max_length=4),
        ),
        migrations.AddField(
            model_name='codequestparticipant',
            name='year',
            field=models.IntegerField(choices=[(2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=2),
        ),
    ]
