# Generated by Django 5.2.2 on 2025-12-30 05:12

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0005_rename_level_to_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequestconsultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='codequest/consultants/'),
        ),
        migrations.AlterField(
            model_name='codequestproject',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='codequest/logos/'),
        ),
    ]
