# Generated by Django 5.2.8 on 2025-12-31 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0006_alter_codequestconsultant_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codequestparticipant',
            name='user_account',
        ),
        migrations.AddField(
            model_name='codequestconsultant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user account (auto-assigned on registration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codequest_consultant_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codequestparticipant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user account (auto-assigned on registration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codequest_participant_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
