# Generated by Django 5.2.8 on 2025-12-31 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0007_add_user_to_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfGroupingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, help_text='Optional team name', max_length=200)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('ready', 'Ready to Finalize'), ('finalized', 'Finalized'), ('disbanded', 'Disbanded')], default='forming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(help_text='Participant who created this team', on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to='codequest.codequestparticipant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_grouping_teams', to='codequest.codequestevent')),
                ('finalized_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_self_grouping_team', to='codequest.codequestgroup')),
            ],
            options={
                'verbose_name': 'Self-Grouping Team',
                'verbose_name_plural': 'Self-Grouping Teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfGroupingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('left', 'Left Team')], default='accepted', max_length=20)),
                ('is_creator', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='codequest.codequestparticipant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='codequest.selfgroupingteam')),
            ],
            options={
                'verbose_name': 'Self-Grouping Membership',
                'verbose_name_plural': 'Self-Grouping Memberships',
                'ordering': ['is_creator', 'joined_at'],
                'unique_together': {('team', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Why do you want to join this team?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(help_text='Participant who wants to join', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests_sent', to='codequest.codequestparticipant')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests_responded', to='codequest.codequestparticipant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='codequest.selfgroupingteam')),
            ],
            options={
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'requester'), name='unique_pending_join_request_per_team')],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message with invitation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(help_text='Participant who received the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='codequest.codequestparticipant')),
                ('sender', models.ForeignKey(help_text='Participant who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='codequest.codequestparticipant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='codequest.selfgroupingteam')),
            ],
            options={
                'verbose_name': 'Group Invitation',
                'verbose_name_plural': 'Group Invitations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'recipient'), name='unique_pending_invitation_per_team_recipient')],
            },
        ),
    ]
