# Generated by Django 5.2.8 on 2025-12-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0008_self_grouping_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestevent',
            name='self_grouping_end_date',
            field=models.DateTimeField(blank=True, help_text='When self-grouping ends (lockdown begins)', null=True),
        ),
        migrations.AddField(
            model_name='codequestevent',
            name='self_grouping_start_date',
            field=models.DateTimeField(blank=True, help_text='When self-grouping can start', null=True),
        ),
    ]
