# Generated by Django 5.1.10 on 2025-07-01 19:42

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_name", models.CharField(max_length=200)),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "registration_link",
                    models.URLField(
                        blank=True,
                        help_text="Registration link for event if any",
                        null=True,
                    ),
                ),
                (
                    "event_image_1",
                    cloudinary.models.CloudinaryField(max_length=255, null=True),
                ),
                (
                    "event_image_2",
                    cloudinary.models.CloudinaryField(max_length=255, null=True),
                ),
                ("event_date", models.DateTimeField(null=True)),
                ("organised_by", models.CharField(max_length=200)),
                (
                    "media_link",
                    models.UUIDField(
                        help_text="Url for more pictures and videos taken at the event",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
