# Generated by Django 5.1.10 on 2025-11-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_media_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, help_text='Event end date and time. If not set, event is assumed to be a single-day event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text='Event start date and time', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='media_link',
            field=models.URLField(blank=True, help_text='Url for more pictures and videos taken at the event (e.g., Google Drive, Dropbox)', null=True),
        ),
    ]
