# Generated by Django 5.2.8 on 2025-12-26 09:28

import calendar_sync.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCalendarToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_type', models.CharField(choices=[('public_events', 'Public Events Calendar'), ('academic', 'Academic Calendar (Exams)')], max_length=20, unique=True)),
                ('token', models.CharField(db_index=True, default=calendar_sync.models.generate_calendar_token, max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Calendar Token',
                'verbose_name_plural': 'Public Calendar Tokens',
            },
        ),
        migrations.CreateModel(
            name='CalendarToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_type', models.CharField(choices=[('full', 'Full Academic Calendar'), ('classes', 'Class Timetable'), ('exams', 'Exam Schedule'), ('events', 'Events Calendar'), ('personal', 'Personal Combined Calendar')], default='personal', max_length=20)),
                ('token', models.CharField(db_index=True, default=calendar_sync.models.generate_calendar_token, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional friendly name for this calendar subscription', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this token', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Token',
                'verbose_name_plural': 'Calendar Tokens',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'calendar_type')},
            },
        ),
    ]
