# Generated by Django 5.1.10 on 2025-07-01 19:42

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutivePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Executive",
            fields=[
                (
                    "executive_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("office_from", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="executives.executiveposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecutiveSocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("snapchat", "Snapchat"),
                            ("tiktok", "TikTok"),
                            ("pinterest", "Pinterest"),
                            ("reddit", "Reddit"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                            ("twitch", "Twitch"),
                            ("flickr", "Flickr"),
                            ("quora", "Quora"),
                            ("medium", "Medium"),
                            ("github", "GitHub"),
                            ("slack", "Slack"),
                        ],
                        max_length=255,
                    ),
                ),
                ("link", models.URLField()),
                (
                    "executive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="executives.executive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Executive social links",
                "verbose_name_plural": "Executive social links",
                "db_table": "executives_social_links",
            },
        ),
    ]
