# Generated by Django 5.1.10 on 2025-11-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['-office_from'], 'verbose_name': 'Executive', 'verbose_name_plural': 'Executives'},
        ),
        migrations.AddField(
            model_name='executive',
            name='office_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='office_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2024/2025)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='office_from',
            field=models.DateTimeField(null=True),
        ),
    ]
