# Generated by Django 5.1.10 on 2025-11-19 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_alter_executive_options_executive_office_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
