# Generated by Django 5.2.8 on 2025-11-22 14:08

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0004_executive_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Committee name (e.g., Technical Committee, Welfare Committee)', max_length=200)),
                ('description', models.TextField(help_text="Brief description of the committee's purpose and responsibilities")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this committee is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocietyHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text="Title of the historical record (e.g., 'Foundation Era', '2020/2021 Administration')", max_length=300)),
                ('session_year', models.CharField(blank=True, help_text='Academic year or period (e.g., 2024/2025)', max_length=20, null=True)),
                ('category', models.CharField(choices=[('founding', 'Founding & Early Years'), ('administration', 'Past Administration'), ('milestone', 'Major Milestone'), ('achievement', 'Notable Achievement'), ('event', 'Historic Event'), ('lecture', 'Past Lecturer')], default='administration', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of this historical period or event')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Provide image URL for historical photos', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Society History',
                'verbose_name_plural': 'Society Histories',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Appointee',
            fields=[
                ('appointee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Provide image URL (Google Drive, Dropbox, etc.) instead of uploading', null=True)),
                ('role', models.CharField(choices=[('head', 'Head'), ('deputy_head', 'Deputy Head'), ('member', 'Member')], default='member', help_text='Role in the committee (Head, Deputy Head, or Member)', max_length=20)),
                ('portfolio', models.TextField(blank=True, help_text='Specific responsibilities and duties of this appointee')),
                ('appointed_from', models.DateTimeField(null=True)),
                ('appointed_to', models.DateTimeField(blank=True, null=True)),
                ('office_year', models.CharField(blank=True, help_text='Academic year (e.g., 2024/2025)', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointee_roles', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='executives.committee')),
            ],
            options={
                'verbose_name': 'Appointee',
                'verbose_name_plural': 'Appointees',
                'ordering': ['committee', 'role', 'user__first_name'],
                'unique_together': {('user', 'committee', 'office_year')},
            },
        ),
        migrations.CreateModel(
            name='AppointeeContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, max_length=200, null=True)),
                ('office_hours', models.CharField(blank=True, help_text='e.g., Mon-Fri 9AM-5PM', max_length=200, null=True)),
                ('appointee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='executives.appointee')),
            ],
            options={
                'verbose_name': 'Appointee Contact Details',
                'verbose_name_plural': 'Appointee Contact Details',
            },
        ),
        migrations.CreateModel(
            name='AppointeeSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('snapchat', 'Snapchat'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('flickr', 'Flickr'), ('quora', 'Quora'), ('medium', 'Medium'), ('github', 'GitHub'), ('slack', 'Slack')], max_length=255)),
                ('link', models.URLField()),
                ('appointee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='executives.appointee')),
            ],
            options={
                'verbose_name': 'Appointee social links',
                'verbose_name_plural': 'Appointee social links',
                'db_table': 'appointee_social_links',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLeader',
            fields=[
                ('leader_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Full name of the leader/executive/lecturer', max_length=200)),
                ('position', models.CharField(help_text='Position held (e.g., President, HOD, Lecturer)', max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or achievements')),
                ('order', models.IntegerField(default=0)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='executives.societyhistory')),
            ],
            options={
                'verbose_name': 'Historical Leader',
                'verbose_name_plural': 'Historical Leaders',
                'ordering': ['order', 'name'],
            },
        ),
    ]
