# Generated by Django 5.2.8 on 2025-11-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0005_committee_societyhistory_appointee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLeader',
        ),
        migrations.DeleteModel(
            name='SocietyHistory',
        ),
    ]
