# Generated by Django 5.2.8 on 2025-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0006_delete_historicalleader_delete_societyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointee',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='List of achievements and accomplishments'),
        ),
        migrations.AddField(
            model_name='appointee',
            name='bio',
            field=models.TextField(blank=True, help_text='Biography/About section for the appointee', null=True),
        ),
        migrations.AddField(
            model_name='appointee',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skills (e.g., ['Python', 'Leadership', 'Public Speaking'])"),
        ),
        migrations.AddField(
            model_name='executive',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='List of achievements and accomplishments'),
        ),
        migrations.AddField(
            model_name='executive',
            name='bio',
            field=models.TextField(blank=True, help_text='Biography/About section for the executive', null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skills (e.g., ['Python', 'Leadership', 'Public Speaking'])"),
        ),
    ]
