# Generated by Django 5.2.8 on 2025-11-22 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0007_appointee_achievements_appointee_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('grant', 'Permission Granted'), ('revoke', 'Permission Revoked'), ('modify', 'Permission Modified')], max_length=20)),
                ('permission_codename', models.CharField(max_length=100)),
                ('permission_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_made', to=settings.AUTH_USER_MODEL)),
                ('target_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to='executives.committee')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_changes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Audit Log',
                'verbose_name_plural': 'Permission Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AppointeePermission',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('permission_codename', models.CharField(help_text="Permission codename (e.g., 'view_committee_reports')", max_length=100)),
                ('permission_name', models.CharField(help_text='Human-readable permission name', max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for temporary permissions', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this permission was granted')),
                ('appointee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to='executives.appointee')),
                ('granted_by', models.ForeignKey(help_text='User (Head/Deputy) who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointee Permission',
                'verbose_name_plural': 'Appointee Permissions',
                'ordering': ['-granted_at'],
                'unique_together': {('appointee', 'permission_codename')},
            },
        ),
    ]
