# Generated by Django 5.2.8 on 2025-11-22 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('executives', '0008_permissionauditlog_appointeepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointeepermission',
            unique_together={('appointee',)},
        ),
        migrations.RemoveField(
            model_name='permissionauditlog',
            name='permission_codename',
        ),
        migrations.RemoveField(
            model_name='permissionauditlog',
            name='permission_name',
        ),
        migrations.AddField(
            model_name='appointeepermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Select permissions from all available backend permissions. Use Ctrl/Cmd to select multiple.', related_name='appointee_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='permissions',
            field=models.ManyToManyField(help_text='Permissions that were granted/revoked/modified', related_name='audit_logs', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='appointeepermission',
            name='granted_by',
            field=models.ForeignKey(help_text='User (Head/Deputy) who granted these permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointeepermission',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily disable all permissions without deleting'),
        ),
        migrations.AlterField(
            model_name='appointeepermission',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about why these permissions were granted'),
        ),
        migrations.RemoveField(
            model_name='appointeepermission',
            name='permission_codename',
        ),
        migrations.RemoveField(
            model_name='appointeepermission',
            name='permission_name',
        ),
    ]
