# Generated by Django 5.2.8 on 2025-11-23 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('executives', '0010_alter_executive_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointeepermission',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Optionally assign permission groups to the user along with individual permissions.', related_name='appointee_permission_groups', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='appointee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'office_year'), name='unique_user_office_year_active'),
        ),
        migrations.AddConstraint(
            model_name='appointee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'head')), fields=('committee', 'office_year'), name='unique_head_per_committee_year'),
        ),
        migrations.AddConstraint(
            model_name='appointee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'deputy_head')), fields=('committee', 'office_year'), name='unique_deputy_per_committee_year'),
        ),
    ]
