# Generated by Django 5.2.8 on 2025-11-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0011_alter_appointee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['position__priority', '-office_from'], 'permissions': (('can_access_mobile_dashboard', 'Can access executive/admin dashboard from mobile'),), 'verbose_name': 'Executive', 'verbose_name_plural': 'Executives'},
        ),
    ]
