# Generated by Django 5.2.8 on 2025-11-23 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0013_executive_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='executive',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('position', 'office_year'), name='unique_position_office_year_active'),
        ),
    ]
