# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0015_alter_permissionauditlog_target_committee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AppointeeImages/'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ExecutiveImages/'),
        ),
    ]
