# Generated by Django 5.2.2 on 2025-12-30 05:02

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0016_alter_appointee_image_alter_executive_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointee',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='AppointeeImages/'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='ExecutiveImages/'),
        ),
    ]
