# Generated by Django 5.2.8 on 2026-02-04 04:03

import django.db.models.deletion
import utils.dynamic_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0017_alter_appointee_image_alter_executive_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('office_year', models.CharField(help_text='Academic year for this report', max_length=20)),
                ('total_meetings', models.PositiveIntegerField(default=0)),
                ('meetings_attended', models.PositiveIntegerField(default=0)),
                ('meetings_absent', models.PositiveIntegerField(default=0)),
                ('meetings_excused', models.PositiveIntegerField(default=0)),
                ('meetings_late', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Attendance rate as percentage', max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'ordering': ['-period_end', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Title/subject of the meeting', max_length=255)),
                ('meeting_type', models.CharField(choices=[('executive', 'Executive Meeting'), ('committee', 'Committee Meeting'), ('general', 'General Meeting'), ('emergency', 'Emergency Meeting'), ('agm', 'Annual General Meeting'), ('joint', 'Joint Meeting'), ('other', 'Other')], default='executive', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description or purpose of the meeting')),
                ('agenda', models.TextField(blank=True, help_text='Meeting agenda items (can be formatted as bullet points)')),
                ('is_executive_meeting', models.BooleanField(default=False, help_text='Check if this is an executive-level meeting (all executives invited)')),
                ('scheduled_date', models.DateField(help_text='Date of the meeting')),
                ('scheduled_time', models.TimeField(help_text='Start time of the meeting')),
                ('end_time', models.TimeField(blank=True, help_text='Expected/actual end time', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('venue', models.CharField(blank=True, help_text='Physical location of the meeting', max_length=255)),
                ('virtual_link', models.URLField(blank=True, help_text='Link for virtual/online meeting (Zoom, Google Meet, etc.)')),
                ('is_virtual', models.BooleanField(default=False, help_text='Is this meeting virtual/online?')),
                ('is_hybrid', models.BooleanField(default=False, help_text='Is this a hybrid meeting (both physical and virtual)?')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('office_year', models.CharField(blank=True, help_text='Academic year (e.g., 2024/2025)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_invitees', models.ManyToManyField(blank=True, help_text='Additional people invited to this meeting', related_name='invited_meetings', to=settings.AUTH_USER_MODEL)),
                ('chaired_by', models.ForeignKey(blank=True, help_text='Person chairing/leading this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_chaired', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(blank=True, help_text='Committee this meeting is for (leave empty for executive meetings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='executives.committee')),
                ('created_by', models.ForeignKey(help_text='Person who created/scheduled this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of this item in the agenda')),
                ('title', models.CharField(help_text='Title of the agenda item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Details about this agenda item')),
                ('duration_minutes', models.PositiveIntegerField(default=10, help_text='Allocated time in minutes')),
                ('is_discussed', models.BooleanField(default=False, help_text='Was this item discussed in the meeting?')),
                ('notes', models.TextField(blank=True, help_text='Notes/outcomes from discussing this item')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='executives.meeting')),
                ('presenter', models.ForeignKey(blank=True, help_text='Person presenting/leading this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Agenda Item',
                'verbose_name_plural': 'Meeting Agenda Items',
                'ordering': ['meeting', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late'), ('left_early', 'Left Early')], default='present', max_length=20)),
                ('arrival_time', models.TimeField(blank=True, help_text='Actual arrival time', null=True)),
                ('departure_time', models.TimeField(blank=True, help_text='Actual departure time (if left early)', null=True)),
                ('excuse_reason', models.TextField(blank=True, help_text='Reason for absence or excuse (if applicable)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='executives.meeting')),
                ('recorded_by', models.ForeignKey(help_text='Person who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Attendance',
                'verbose_name_plural': 'Meeting Attendances',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('minutes_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(blank=True, help_text='Full text content of the meeting minutes')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of key points and decisions')),
                ('minutes_file', models.FileField(blank=True, help_text='Upload the minutes document (PDF, DOCX, etc.)', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='MeetingMinutes/')),
                ('minutes_file_url', models.URLField(blank=True, help_text='Alternative: Provide URL to minutes document (Google Drive, Dropbox, etc.)', null=True)),
                ('decisions', models.JSONField(blank=True, default=list, help_text='List of decisions made during the meeting')),
                ('action_items', models.JSONField(blank=True, default=list, help_text="List of action items with assignees and deadlines. Format: [{'task': '...', 'assignee': '...', 'deadline': '...'}]")),
                ('is_approved', models.BooleanField(default=False, help_text='Have these minutes been approved?')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Person who approved the minutes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_approved', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='executives.meeting')),
                ('prepared_by', models.ForeignKey(help_text='Person who prepared the minutes (usually secretary)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Minutes',
                'verbose_name_plural': 'Meeting Minutes',
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_date', 'status'], name='executives__schedul_d31e78_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['committee', 'status'], name='executives__committ_a9a1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'status'], name='executives__meeting_dfc3de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingagendaitem',
            unique_together={('meeting', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('meeting', 'user')},
        ),
    ]
