# Generated by Django 5.2.8 on 2025-11-22 14:24

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text="Title of the historical record (e.g., 'Foundation Era', '2020/2021 Administration')", max_length=300)),
                ('session_year', models.CharField(blank=True, help_text='Academic year or period (e.g., 2024/2025)', max_length=20, null=True)),
                ('category', models.CharField(choices=[('founding', 'Founding & Early Years'), ('administration', 'Past Administration'), ('milestone', 'Major Milestone'), ('achievement', 'Notable Achievement'), ('event', 'Historic Event'), ('lecture', 'Past Lecturer'), ('other', 'Other')], default='administration', help_text='Category of this historical record', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of this historical period or event')),
                ('start_date', models.DateField(blank=True, help_text='Start date of this period', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date of this period (leave blank for ongoing)', null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this historical record', max_length=255, null=True, verbose_name='image')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Provide image URL (Google Drive, Dropbox, etc.) instead of uploading', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first in same category)')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this record is visible on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Society History Record',
                'verbose_name_plural': 'Society History Records',
                'db_table': 'history_society_history',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMilestone',
            fields=[
                ('milestone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Title of the milestone or achievement', max_length=300)),
                ('description', models.TextField(help_text='Description of what was achieved')),
                ('date', models.DateField(blank=True, help_text='Date when this milestone was achieved', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(help_text='The historical period this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='history.societyhistory')),
            ],
            options={
                'verbose_name': 'Historical Milestone',
                'verbose_name_plural': 'Historical Milestones',
                'db_table': 'history_milestone',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLeader',
            fields=[
                ('leader_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Full name of the leader/executive/lecturer', max_length=200)),
                ('position', models.CharField(help_text='Position held (e.g., President, HOD, Senior Lecturer, Founder)', max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload a profile photo', max_length=255, null=True, verbose_name='image')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief biography, achievements, or contributions')),
                ('order', models.IntegerField(default=0, help_text='Display order within the historical period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(help_text='The historical period this leader belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='history.societyhistory')),
            ],
            options={
                'verbose_name': 'Historical Leader',
                'verbose_name_plural': 'Historical Leaders',
                'db_table': 'history_historical_leader',
                'ordering': ['order', 'name'],
            },
        ),
    ]
