# Generated by Django 5.2.2 on 2025-12-30 05:02

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_historicalleader_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleader',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a profile photo', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='HistoricalLeaders/'),
        ),
        migrations.AlterField(
            model_name='societyhistory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this historical record', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='HistoryImages/'),
        ),
    ]
