# Generated by Django 5.2.8 on 2026-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0002_add_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='notify_low_stock',
            field=models.BooleanField(default=True, help_text='Receive notifications when items are low in stock'),
        ),
        migrations.AddField(
            model_name='seller',
            name='notify_messages',
            field=models.BooleanField(default=True, help_text='Receive notifications for new customer messages'),
        ),
        migrations.AddField(
            model_name='seller',
            name='notify_new_orders',
            field=models.BooleanField(default=True, help_text='Receive notifications for new orders'),
        ),
        migrations.AddField(
            model_name='seller',
            name='notify_payouts',
            field=models.BooleanField(default=True, help_text='Receive notifications for payout updates'),
        ),
        migrations.AddField(
            model_name='seller',
            name='notify_reviews',
            field=models.BooleanField(default=True, help_text='Receive notifications for new reviews'),
        ),
    ]
