# Generated by Django 5.2.8 on 2026-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0003_add_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='return_policy',
            field=models.TextField(blank=True, help_text="Seller's return and refund policy"),
        ),
        migrations.AddField(
            model_name='seller',
            name='shipping_policy',
            field=models.TextField(blank=True, help_text="Seller's shipping policy and estimated delivery times"),
        ),
    ]
