# Generated by Django 5.2.8 on 2026-01-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_shipping_address_model'),
        ('el_mercado', '0005_add_seller_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text="Reference to buyer's saved shipping address", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.shippingaddress'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='shipping_digital_address',
            field=models.CharField(blank=True, help_text='Ghana Post GPS Digital Address (e.g., GA-123-4567)', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='shipping_landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easy location', max_length=255),
        ),
    ]
