# Generated by Django 5.2.8 on 2026-01-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0006_add_shipping_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_code',
            field=models.CharField(blank=True, help_text='6-digit code buyer gives to seller to confirm delivery', max_length=6),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_verified',
            field=models.BooleanField(default=False, help_text='Whether delivery has been verified with the code'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
