# Generated by Django 5.2.8 on 2026-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0007_add_delivery_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT_PENDING', 'Credit (Pending)'), ('RELEASE', 'Release to Available'), ('WITHDRAWAL', 'Withdrawal'), ('FEE', 'Platform Fee'), ('REFUND_DEDUCT', 'Refund Deduction'), ('ADJUSTMENT', 'Manual Adjustment'), ('BONUS', 'Bonus/Incentive'), ('PAYOUT_HOLD', 'Payout Hold'), ('PAYOUT_COMPLETE', 'Payout Completed'), ('PAYOUT_REFUND', 'Payout Refunded')], max_length=20),
        ),
    ]
