# Generated by Django 5.2.8 on 2026-01-18 21:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0008_add_wallet_transaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount seller receives after processing fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for processing the payout', max_digits=12),
        ),
    ]
