# Generated by Django 5.2.8 on 2026-01-19 16:20

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_mercado', '0009_payoutrequest_net_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('STANDARD', 'Standard Products'), ('DIGITAL', 'Digital Products'), ('SERVICES', 'Services'), ('HANDMADE', 'Handmade/Custom Items')], max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Commission percentage for this category type', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Rate',
                'verbose_name_plural': 'Commission Rates',
                'ordering': ['category_type'],
            },
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='payment_processing_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Fixed payment gateway fee (GHS)', max_digits=10),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='payment_processing_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.5'), help_text='Payment gateway fee percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='payout_processing_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Payout processing fee percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='payout_transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Fee per payout/withdrawal (GHS)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='default_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default platform commission percentage (fallback)', max_digits=5),
        ),
    ]
