# Generated by Django 5.2.8 on 2025-12-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_donation_transaction_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_tr_merchan_d48ab3_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchandise_collected',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchandise_collected_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchandise_validation_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='variant_selections',
        ),
    ]
