# Generated by Django 5.2.8 on 2025-12-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycheck',
            name='admission_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Admission'), ('FEE_PAYING', 'Fee-Paying/Parallel Program'), ('MATURE', 'Mature Applicant (25+ with experience)')], default='REGULAR', help_text='Type of admission pathway', max_length=20),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='meets_feepaying_requirements',
            field=models.BooleanField(default=False, help_text='Meets fee-paying requirements'),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='meets_regular_requirements',
            field=models.BooleanField(default=False, help_text='Meets regular admission requirements'),
        ),
    ]
