# Generated by Django 5.2.8 on 2025-12-12 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_populate_grade_mappings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsapphelpdesk',
            options={'ordering': ['-academic_year', 'program'], 'verbose_name': 'WhatsApp Helpdesk Group', 'verbose_name_plural': 'WhatsApp Helpdesk Groups'},
        ),
        migrations.RemoveField(
            model_name='whatsapphelpdesk',
            name='accessed_at',
        ),
        migrations.RemoveField(
            model_name='whatsapphelpdesk',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='whatsapphelpdesk',
            name='email',
        ),
        migrations.RemoveField(
            model_name='whatsapphelpdesk',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='whatsapphelpdesk',
            name='student_name',
        ),
        migrations.AddField(
            model_name='whatsapphelpdesk',
            name='academic_year',
            field=models.CharField(default='2025/2026', help_text='Academic year (e.g., 2025/2026)', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsapphelpdesk',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsapphelpdesk',
            name='group_description',
            field=models.TextField(blank=True, help_text='Description shown to students before joining'),
        ),
        migrations.AddField(
            model_name='whatsapphelpdesk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='whatsapphelpdesk',
            name='access_count',
            field=models.IntegerField(default=0, help_text='Total number of times link was accessed'),
        ),
        migrations.AlterField(
            model_name='whatsapphelpdesk',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this group currently active for new students?'),
        ),
        migrations.AlterField(
            model_name='whatsapphelpdesk',
            name='program',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], help_text='Program this WhatsApp group is for', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsapphelpdesk',
            name='whatsapp_group_link',
            field=models.URLField(help_text='WhatsApp group invite link for admitted students'),
        ),
        migrations.CreateModel(
            name='WhatsAppAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(help_text="Student's application ID", max_length=100)),
                ('student_name', models.CharField(help_text='Student name from KNUSTAdmission', max_length=300)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('helpdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='admissions.whatsapphelpdesk')),
            ],
            options={
                'verbose_name': 'WhatsApp Access Log',
                'verbose_name_plural': 'WhatsApp Access Logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
