# Generated by Django 5.2.8 on 2026-01-03 13:02

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_alter_admissionguideline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='knustadmission',
            name='academic_year',
            field=models.CharField(default=admissions.models.get_current_academic_year, help_text='Academic year (e.g., 2025/2026)', max_length=20),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='admission_status',
            field=models.CharField(choices=[('REGULAR', 'Regular/WASSCE'), ('FEE_PAYING', 'Fee Paying'), ('MATURE', 'Mature/Other'), ('INTERNATIONAL', 'International'), ('LESS_ENDOWED', 'Less Endowed Schools'), ('NMTC', 'NMTC Upgrade'), ('UNKNOWN', 'Unknown')], default='REGULAR', help_text='Type of admission', max_length=20),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='programme_code',
            field=models.CharField(choices=[('CS', 'BSc. Computer Science'), ('IT', 'BSc. Information Technology')], default='CS', help_text='Programme code (CS or IT)', max_length=2),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='source',
            field=models.CharField(choices=[('SCRAPER', 'Web Scraper'), ('UPLOAD', 'Excel Upload'), ('MANUAL', 'Manual Entry')], default='SCRAPER', help_text='How this record was added', max_length=20),
        ),
        migrations.AlterField(
            model_name='knustadmission',
            name='applicant_id',
            field=models.CharField(help_text='Unique applicant ID from KNUST', max_length=100),
        ),
        migrations.AlterField(
            model_name='knustadmission',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the data was first added'),
        ),
        migrations.AlterField(
            model_name='knustadmission',
            name='programme',
            field=models.CharField(help_text='Programme admitted to (e.g., BSc. Computer Science)', max_length=200),
        ),
        migrations.AlterField(
            model_name='knustadmission',
            name='status',
            field=models.TextField(blank=True, help_text='Additional admission status/info (from scraper)'),
        ),
        migrations.AlterUniqueTogether(
            name='knustadmission',
            unique_together={('applicant_id', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='knustadmission',
            index=models.Index(fields=['academic_year'], name='admissions__academi_f4fdcb_idx'),
        ),
        migrations.AddIndex(
            model_name='knustadmission',
            index=models.Index(fields=['programme_code'], name='admissions__program_704891_idx'),
        ),
        migrations.AddIndex(
            model_name='knustadmission',
            index=models.Index(fields=['admission_status'], name='admissions__admissi_284f78_idx'),
        ),
    ]
