# Generated by Django 5.2.8 on 2026-01-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_knustadmission_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knustadmission',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_HALL', 'Traditional Hall'), ('HOSTEL', 'Hostel'), ('OFF_CAMPUS', 'Off Campus')], help_text='Type of accommodation (Hall, Hostel, or Off-campus)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='accommodation_updated_at',
            field=models.DateTimeField(blank=True, help_text='When accommodation details were last updated', null=True),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='accommodation_verified',
            field=models.BooleanField(default=False, help_text='Whether the student has verified and submitted their accommodation details'),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='campus_status',
            field=models.CharField(blank=True, choices=[('ON_CAMPUS', 'On Campus'), ('OFF_CAMPUS', 'Off Campus')], help_text='Whether student lives on or off campus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='hall_name',
            field=models.CharField(blank=True, choices=[('UNITY_HALL', 'Unity Hall (Conti)'), ('QUEENS_HALL', "Queen's Hall"), ('INDEPENDENCE_HALL', 'Independence Hall (Indece)'), ('AFRICA_HALL', 'Africa Hall (Katanga)'), ('REPUBLIC_HALL', 'Republic Hall (Rep)'), ('UNIVERSITY_HALL', 'University Hall (Brunei)'), ('OTHER', 'Other')], help_text='Name of traditional hall (if in hall)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='hostel_name',
            field=models.CharField(blank=True, help_text='Name of hostel (if in hostel)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Student's phone number", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='knustadmission',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room number', max_length=50, null=True),
        ),
    ]
