# Generated by Django 5.2.8 on 2026-01-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_knustadmission_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsapphelpdesk',
            options={'ordering': ['-academic_year', 'program', 'group_type'], 'verbose_name': 'WhatsApp Group', 'verbose_name_plural': 'WhatsApp Groups'},
        ),
        migrations.AddField(
            model_name='whatsapphelpdesk',
            name='group_type',
            field=models.CharField(choices=[('ADMISSION', 'Admission Helpdesk'), ('ACADEMIC', 'Academic/Class Group')], default='ADMISSION', help_text='Type of group: ADMISSION for helpdesk, ACADEMIC for official class groups', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsapphelpdesk',
            name='program',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], help_text='Program this WhatsApp group is for', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='whatsapphelpdesk',
            unique_together={('program', 'group_type', 'academic_year')},
        ),
    ]
