# Generated by Django 5.2.8 on 2026-01-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_alter_whatsapphelpdesk_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knustadmission',
            name='hall_name',
            field=models.CharField(blank=True, choices=[('UNITY_HALL', 'Unity Hall (Conti)'), ('QUEENS_HALL', "Queen's Hall"), ('INDEPENDENCE_HALL', 'Independence Hall (Indece)'), ('AFRICA_HALL', 'Africa Hall'), ('REPUBLIC_HALL', 'Republic Hall (Rep)'), ('UNIVERSITY_HALL', 'University Hall (Katanga)'), ('OTHER', 'Other')], help_text='Name of traditional hall (if in hall)', max_length=50, null=True),
        ),
    ]
