# Generated by Django 5.1.10 on 2025-11-15 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Machine Learning, Network Security', max_length=100)),
            ],
            options={
                'verbose_name': 'Research Area',
                'verbose_name_plural': 'Research Areas',
                'db_table': 'faculty_research_areas',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('SENIOR_LECTURER', 'Senior Lecturer'), ('LECTURER', 'Lecturer'), ('ASSISTANT_LECTURER', 'Assistant Lecturer'), ('PART_TIME_LECTURER', 'Part-Time Lecturer')], max_length=50)),
                ('specialization', models.CharField(help_text='e.g., Artificial Intelligence, Computer Networks', max_length=255)),
                ('bio', models.TextField(help_text='Brief description of research focus and expertise')),
                ('publications_count', models.IntegerField(default=0)),
                ('awards_count', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(help_text='e.g., CS Building, Room 302', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'faculty_staff',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AddField(
            model_name='researcharea',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_areas', to='faculty.staff'),
        ),
    ]
