# Generated by Django 5.2.2 on 2025-12-30 05:12

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_staff_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='faculty/'),
        ),
    ]
