# Generated by Django 5.1.10 on 2025-07-01 19:42

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "news_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("reported_by", models.CharField(max_length=100)),
                ("report", models.TextField()),
                ("minutes_read", models.IntegerField(default=0)),
                (
                    "head_image",
                    cloudinary.models.CloudinaryField(max_length=255, null=True),
                ),
                (
                    "back_image",
                    cloudinary.models.CloudinaryField(max_length=255, null=True),
                ),
                ("views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updted", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "News/Blogs",
                "verbose_name_plural": "News/Blogs",
                "db_table": "news_blogs",
            },
        ),
    ]
