# Generated by Django 5.1.10 on 2025-11-19 11:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='back_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide back image URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='head_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide head image URL instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='head_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
