# Generated by Django 5.2.2 on 2025-12-30 05:02

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_back_image_alter_news_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='back_image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='NewsImages/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='head_image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='NewsImages/'),
        ),
    ]
