# Generated by Django 5.1.10 on 2025-11-15 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Full name of the faculty member', max_length=255)),
                ('title', models.CharField(help_text='Academic title (e.g., Prof., Dr., Mr., Mrs.)', max_length=100)),
                ('rank', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('SENIOR_LECTURER', 'Senior Lecturer'), ('LECTURER', 'Lecturer'), ('ASSISTANT_LECTURER', 'Assistant Lecturer'), ('PART_TIME_LECTURER', 'Part-Time Lecturer')], default='LECTURER', help_text='Academic rank/position', max_length=50)),
                ('position', models.CharField(blank=True, help_text='Special position (e.g., Head of Department)', max_length=255, null=True)),
                ('specialization', models.CharField(help_text='Main area of specialization', max_length=255)),
                ('bio', models.TextField(help_text='Brief biography or research focus description')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('office_location', models.CharField(help_text='Office location (e.g., CS Building, Room 302)', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Faculty member photo', null=True, upload_to='faculty/')),
                ('publications_count', models.IntegerField(default=0, help_text='Number of publications')),
                ('awards_count', models.IntegerField(default=0, help_text='Number of awards received')),
                ('research_areas', models.JSONField(default=list, help_text='List of research areas/tags')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the faculty member is currently active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'db_table': 'faculty',
                'ordering': ['order', 'name'],
            },
        ),
    ]
