# Generated by Django 5.1.10 on 2025-11-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_researcharea_staff_delete_faculty_researcharea_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Department & Staff'},
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Currently Active'), ('ON_LEAVE', 'On Leave'), ('RETIRED', 'Retired'), ('FORMER', 'Former Staff')], default='ACTIVE', help_text='Current employment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/hide on public website'),
        ),
    ]
