# Generated by Django 5.1.10 on 2025-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_staff_options_staff_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True),
        ),
    ]
