# Generated by Django 5.1.10 on 2025-07-01 19:42

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("credit_hours", models.IntegerField(null=True)),
                ("course_name", models.CharField(max_length=200, null=True)),
                ("course_code", models.CharField(max_length=200, unique=True)),
                ("level", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InternshipOpportunities",
            fields=[
                (
                    "internship_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("campany_name", models.CharField(max_length=255)),
                ("image", cloudinary.models.CloudinaryField(max_length=255)),
                ("description", models.TextField()),
                ("registration_link", models.URLField()),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Internship",
                "verbose_name_plural": "Internships",
            },
        ),
        migrations.CreateModel(
            name="AcademicSlides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A simple title about the resource",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("file", cloudinary.models.CloudinaryField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Academic Slides",
            },
        ),
        migrations.CreateModel(
            name="OnlineTutorialTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A simple title about the resource",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("link", models.URLField(verbose_name="resource_link")),
                (
                    "type_of_resource",
                    models.CharField(
                        choices=[
                            ("slides", "slides"),
                            ("video", "video"),
                            ("article", "article"),
                            ("audio", "audio"),
                            ("file", "file"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_tips",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Online Tutorial Tips",
            },
        ),
        migrations.CreateModel(
            name="PastQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A simple title about the resource",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("file", cloudinary.models.CloudinaryField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_questions",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Past Questions",
            },
        ),
    ]
