# Generated by Django 5.1.10 on 2025-11-09 10:55

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(choices=[('Prof.', 'Professor'), ('Dr.', 'Doctor'), ('Mr.', 'Mister'), ('Mrs.', 'Mistress'), ('Ms.', 'Miss')], default='Mr.', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Area of expertise (e.g., Artificial Intelligence, Networks)', max_length=200, null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief biography of the lecturer', null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the lecturer currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level', 'semester', 'course_code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the course content', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be completed before taking this course', related_name='required_for', to='academics.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('both', 'Both Semesters')], default='1', help_text='Which semester is this course offered?', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(blank=True, help_text='Lecturers teaching this course', related_name='courses', to='academics.lecturer'),
        ),
    ]
