# Generated by Django 5.1.10 on 2025-11-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_course_lecturers_course_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], default='CS', help_text='Which program does this course belong to? (Computer Science or Information Technology)', max_length=10),
        ),
    ]
