# Generated by Django 5.2.8 on 2025-12-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_academicslides_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicslides',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onlinetutorialtips',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pastquestions',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
