# Generated by Django 5.1.10 on 2025-11-19 10:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
