# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timeline_image_url_alter_timeline_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='TimelineImages/'),
        ),
    ]
