# Generated by Django 5.2.8 on 2025-12-24 01:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance in the donation wallet', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount ever received', max_digits=15)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount ever withdrawn', max_digits=15)),
                ('total_donations_count', models.PositiveIntegerField(default=0, help_text='Total number of donations received')),
                ('total_donors_count', models.PositiveIntegerField(default=0, help_text='Total unique donors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation Wallet',
                'verbose_name_plural': 'Donation Wallet',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('donor_name', models.CharField(blank=True, help_text="Name to display (or 'Anonymous')", max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If true, donor name will be hidden publicly')),
                ('show_amount', models.BooleanField(default=True, help_text='If true, donation amount will be shown publicly')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('message', models.TextField(blank=True, help_text='Optional message from donor')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('gateway', models.CharField(default='paystack', max_length=50)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, help_text='User who made the donation (null for guest donations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('recipient_name', models.CharField(help_text='Name of recipient/vendor', max_length=255)),
                ('recipient_account', models.CharField(blank=True, help_text='Account number or mobile money number', max_length=255)),
                ('recipient_bank', models.CharField(blank=True, help_text='Bank name or mobile money provider', max_length=255)),
                ('purpose', models.CharField(help_text='What is this withdrawal for?', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the expense')),
                ('category', models.CharField(choices=[('events', 'Events & Programs'), ('equipment', 'Equipment & Supplies'), ('welfare', 'Student Welfare'), ('operations', 'Operations'), ('scholarships', 'Scholarships & Awards'), ('marketing', 'Marketing & Promotion'), ('other', 'Other')], default='other', help_text='Category of expense', max_length=100)),
                ('receipt_image', models.ImageField(blank=True, help_text='Receipt or proof of payment', null=True, upload_to='donations/receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Wallet balance before withdrawal', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after withdrawal', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(help_text='Admin who initiated the withdrawal', on_delete=django.db.models.deletion.PROTECT, related_name='initiated_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Withdrawal',
                'verbose_name_plural': 'Donation Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation Received'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='donations.donation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_transactions_performed', to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='donations.donationwithdrawal')),
            ],
            options={
                'verbose_name': 'Donation Transaction',
                'verbose_name_plural': 'Donation Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_donated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount donated by this user', max_digits=15)),
                ('donation_count', models.PositiveIntegerField(default=0, help_text='Number of donations made')),
                ('first_donation_at', models.DateTimeField(blank=True, null=True)),
                ('last_donation_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Profile',
                'verbose_name_plural': 'Donor Profiles',
            },
        ),
    ]
