# Generated by Django 5.2.8 on 2025-12-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationwithdrawal',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical Emergency'), ('financial_hardship', 'Financial Hardship'), ('bereavement', 'Bereavement Support'), ('accommodation', 'Accommodation Support'), ('feeding', 'Feeding Support'), ('welfare', 'General Welfare'), ('emergency', 'Emergency Support'), ('other', 'Other Welfare')], default='other', help_text='Category of expense', max_length=100),
        ),
    ]
