# Generated by Django 5.2.8 on 2025-12-24 02:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_show_amount_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationwithdrawal',
            name='gateway',
            field=models.CharField(blank=True, default='paystack', max_length=50),
        ),
        migrations.AddField(
            model_name='donationwithdrawal',
            name='gateway_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged by gateway for transfer', max_digits=10),
        ),
        migrations.AddField(
            model_name='donationwithdrawal',
            name='gateway_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack recipient code', max_length=255),
        ),
        migrations.AddField(
            model_name='donationwithdrawal',
            name='gateway_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Gateway transaction reference', max_length=255),
        ),
        migrations.AddField(
            model_name='donationwithdrawal',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Full gateway response data'),
        ),
        migrations.AddField(
            model_name='donationwithdrawal',
            name='gateway_transfer_code',
            field=models.CharField(blank=True, db_index=True, help_text='Paystack transfer code', max_length=255),
        ),
        migrations.AddField(
            model_name='donationwithdrawal',
            name='recipient_bank_code',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('vod', 'Vodafone Cash'), ('atl', 'AirtelTigo Money'), ('gcb', 'GCB Bank'), ('ecobank', 'Ecobank Ghana'), ('absa', 'Absa Bank Ghana'), ('stanbic', 'Stanbic Bank'), ('uba', 'UBA Ghana'), ('fidelity', 'Fidelity Bank'), ('calbank', 'CalBank'), ('zenith', 'Zenith Bank'), ('access', 'Access Bank'), ('gt_bank', 'GT Bank'), ('prudential', 'Prudential Bank'), ('fnb', 'First National Bank'), ('republic', 'Republic Bank'), ('societe', 'Societe Generale'), ('adb', 'Agricultural Development Bank'), ('nib', 'National Investment Bank'), ('other', 'Other')], help_text='Bank/Provider code for gateway transfers', max_length=50),
        ),
        migrations.AddField(
            model_name='donationwithdrawal',
            name='transfer_method',
            field=models.CharField(choices=[('manual', 'Manual Transfer'), ('gateway', 'Gateway Transfer (Paystack)')], default='manual', help_text='How the transfer will be processed', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationwithdrawal',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Receipt or proof of payment (for manual transfers)', null=True, upload_to='donations/receipts/'),
        ),
    ]
