# Generated by Django 5.2.8 on 2025-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_add_gateway_transfer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationwithdrawal',
            name='receipt_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide receipt image URL instead of uploading', null=True),
        ),
    ]
