# Generated by Django 5.2.2 on 2025-12-30 05:12

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donationwithdrawal_receipt_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationwithdrawal',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Receipt or proof of payment (for manual transfers)', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='donations/receipts/'),
        ),
    ]
