# Generated by Django 5.1.10 on 2025-11-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_lecturer_alter_course_options_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Lecturer teaching this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.lecturer'),
        ),
    ]
