# Generated by Django 5.1.10 on 2025-11-19 11:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicslides',
            name='file_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide file URL (Google Drive, Dropbox, etc.) instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='internshipopportunities',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide flyer URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide profile image URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='pastquestions',
            name='file_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide file URL (Google Drive, Dropbox, etc.) instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='academicslides',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internshipopportunities',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastquestions',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
