# Generated by Django 5.2.8 on 2025-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_academicslides_approved_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicslides',
            index=models.Index(fields=['course', 'approved'], name='academics_a_course__9cf918_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'semester'], name='academics_c_level_e326bb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['program'], name='academics_c_program_cc3519_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['lecturer'], name='academics_c_lecture_2ea326_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='academics_c_course__c22a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinetutorialtips',
            index=models.Index(fields=['course', 'approved'], name='academics_o_course__0add4e_idx'),
        ),
        migrations.AddIndex(
            model_name='pastquestions',
            index=models.Index(fields=['course', 'approved'], name='academics_p_course__569830_idx'),
        ),
    ]
