# Generated by Django 5.2.8 on 2025-12-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_rename_level_to_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['year', 'semester', 'course_code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='academics_c_year_c32741_idx',
            old_name='academics_c_year_e326bb_idx',
        ),
    ]
