# Generated by Django 5.2.2 on 2025-12-30 05:02

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_academicslides_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicslides',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='AcademicSlides/'),
        ),
        migrations.AlterField(
            model_name='internshipopportunities',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='InternshipFlyers/'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='LecturerProfiles/'),
        ),
        migrations.AlterField(
            model_name='pastquestions',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='PastQuestions/'),
        ),
    ]
