# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_back_image_url_news_head_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='NewsImages/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='NewsImages/'),
        ),
    ]
