# Generated by Django 5.1.10 on 2025-11-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codequestconsultant',
            options={'ordering': ['student_name'], 'verbose_name': 'Code Quest Consultant', 'verbose_name_plural': 'Code Quest Consultants'},
        ),
        migrations.RemoveField(
            model_name='codequestconsultant',
            name='company_organization',
        ),
        migrations.RemoveField(
            model_name='codequestconsultant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='codequestconsultant',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='codequestconsultant',
            name='student_id',
            field=models.CharField(default='TEMP000', help_text='Student ID number', max_length=20),
        ),
        migrations.AddField(
            model_name='codequestconsultant',
            name='student_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codequestconsultant',
            name='year_level',
            field=models.CharField(choices=[('L300', 'Level 300 (3rd Year)'), ('L400', 'Level 400 (4th Year)')], default='L300', help_text='Academic year level', max_length=4),
        ),
        migrations.AlterField(
            model_name='codequestconsultant',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief introduction and skills'),
        ),
    ]
