# Generated by Django 5.2.8 on 2025-12-06 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guide_type', models.CharField(choices=[('VOUCHER', 'Voucher Purchase'), ('REGISTRATION', 'Account Registration'), ('APPLICATION', 'Application Form'), ('DOCUMENTS', 'Required Documents'), ('STATUS', 'Status Checking'), ('GENERAL', 'General Information')], max_length=20)),
                ('content', models.TextField(help_text='Detailed step-by-step instructions')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('portal_url', models.URLField(blank=True, help_text='Related portal URL')),
                ('video_url', models.URLField(blank=True, help_text='Tutorial video URL')),
                ('image', models.ImageField(blank=True, upload_to='admission_guides/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['guide_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('REQUIREMENTS', 'Requirements'), ('APPLICATION', 'Application Process'), ('FEES', 'Fees & Payment'), ('PROGRAMS', 'Programs'), ('DEADLINES', 'Deadlines'), ('DOCUMENTS', 'Documents'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('APPLICATION_OPEN', 'Application Opens'), ('APPLICATION_CLOSE', 'Application Closes'), ('RESULTS', 'Results Release'), ('ORIENTATION', 'Orientation'), ('REGISTRATION', 'Registration'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('academic_year', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGradeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, unique=True)),
                ('numerical_value', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['numerical_value'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('aggregate_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(54)])),
                ('core_math_grade', models.CharField(max_length=2)),
                ('english_grade', models.CharField(max_length=2)),
                ('integrated_science_grade', models.CharField(max_length=2)),
                ('social_studies_grade', models.CharField(max_length=2)),
                ('elective_math_grade', models.CharField(blank=True, max_length=2)),
                ('physics_grade', models.CharField(blank=True, max_length=2)),
                ('chemistry_grade', models.CharField(blank=True, max_length=2)),
                ('biology_grade', models.CharField(blank=True, max_length=2)),
                ('elective_ict_grade', models.CharField(blank=True, max_length=2)),
                ('other_elective_1', models.CharField(blank=True, max_length=50)),
                ('other_elective_1_grade', models.CharField(blank=True, max_length=2)),
                ('other_elective_2', models.CharField(blank=True, max_length=50)),
                ('other_elective_2_grade', models.CharField(blank=True, max_length=2)),
                ('preferred_program', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], max_length=2)),
                ('is_eligible', models.BooleanField(default=False)),
                ('eligibility_details', models.JSONField(default=dict, help_text='Detailed eligibility breakdown')),
                ('recommendations', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eligibility Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], max_length=2)),
                ('academic_year', models.CharField(help_text='e.g., 2025/2026', max_length=20)),
                ('aggregate_cutoff', models.IntegerField(help_text='Minimum aggregate score (6 is best, 54 is worst)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(54)])),
                ('core_math_min_grade', models.CharField(default='C6', help_text='Minimum grade for Core Mathematics (e.g., A1, B2, C6)', max_length=2)),
                ('english_min_grade', models.CharField(default='C6', help_text='Minimum grade for English Language', max_length=2)),
                ('integrated_science_min_grade', models.CharField(default='C6', help_text='Minimum grade for Integrated Science', max_length=2)),
                ('social_studies_min_grade', models.CharField(default='C6', help_text='Minimum grade for Social Studies', max_length=2)),
                ('elective_math_required', models.BooleanField(default=True, help_text='Is Elective Mathematics required?')),
                ('elective_math_min_grade', models.CharField(default='C6', help_text='Minimum grade for Elective Mathematics', max_length=2)),
                ('physics_required', models.BooleanField(default=True, help_text='Is Physics required?')),
                ('physics_min_grade', models.CharField(default='C6', help_text='Minimum grade for Physics', max_length=2)),
                ('science_electives_required', models.IntegerField(default=2, help_text='Minimum number of science electives required')),
                ('additional_requirements', models.TextField(blank=True, help_text='Any additional requirements or notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Admission Criteria',
                'ordering': ['-academic_year', 'program'],
                'unique_together': {('program', 'academic_year')},
            },
        ),
    ]
