# Generated by Django 5.2.8 on 2025-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_eligibilitycheck_admission_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppHelpdesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(help_text="Student's KNUST application ID", max_length=50, unique=True)),
                ('student_name', models.CharField(help_text='Full name of student', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('program', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], help_text='Program applied for', max_length=2)),
                ('whatsapp_group_link', models.URLField(help_text='WhatsApp group invite link')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(blank=True, help_text='Last time link was accessed', null=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times link was accessed')),
            ],
            options={
                'verbose_name': 'WhatsApp Helpdesk',
                'verbose_name_plural': 'WhatsApp Helpdesk Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='eligibilitycheck',
            name='user',
        ),
    ]
