# Generated by Django 5.2.8 on 2025-12-06 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_whatsapphelpdesk_remove_eligibilitycheck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycheck',
            name='completion_year',
            field=models.IntegerField(default=2024, help_text='Year completed SHS (e.g., 2024)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='full_name',
            field=models.CharField(default='Unknown', help_text='Full name of prospective student', max_length=200),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='shs_school',
            field=models.CharField(default='Not Specified', help_text='Senior High School attended', max_length=300),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='email',
            field=models.EmailField(default='unknown@example.com', help_text="Student's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='phone',
            field=models.CharField(default='0000000000', help_text="Student's phone number", max_length=15),
        ),
        migrations.AlterField(
            model_name='whatsapphelpdesk',
            name='application_id',
            field=models.CharField(help_text="Student's 8-digit application ID", max_length=8, unique=True),
        ),
    ]
