# Generated by Django 5.2.8 on 2025-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_eligibilitycheck_completion_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KNUSTAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(help_text='Unique applicant ID from KNUST', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Full name of applicant', max_length=300)),
                ('programme', models.CharField(help_text='Programme admitted to', max_length=200)),
                ('status', models.TextField(help_text='Admission status/info')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When the data was first scraped')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the data was updated')),
            ],
            options={
                'verbose_name': 'KNUST Admission',
                'verbose_name_plural': 'KNUST Admissions',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['applicant_id'], name='admissions__applica_6454dc_idx'), models.Index(fields=['-fetched_at'], name='admissions__fetched_60fea6_idx')],
            },
        ),
    ]
