# Generated by Django 5.2.8 on 2025-12-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_knustadmission'),
    ]

    operations = [
    ]
