# Generated by Django 5.2.8 on 2025-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_whatsapphelpdesk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionguideline',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True),
        ),
    ]
