# Generated by Django 5.2.2 on 2025-12-30 05:12

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_admissionguideline_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionguideline',
            name='image',
            field=models.ImageField(blank=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='admission_guides/'),
        ),
    ]
