# Generated by Django 5.2.8 on 2025-11-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_merchandise_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_merchan_d48ab3_idx',
            old_name='payments_tr_merchan_idx',
        ),
    ]
