# Generated by Django 5.2.8 on 2025-12-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_payments_tr_merchan_idx_payments_tr_merchan_d48ab3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='variant_selections',
            field=models.JSONField(blank=True, default=list, help_text="Customer's color/size preferences for product variants. Format: [{'color_id': 'uuid', 'size_id': 'uuid', 'quantity': 1}]"),
        ),
    ]
