# Generated by Django 5.2.8 on 2025-12-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_variant_selections_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('donation', 'Donation'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('transfer', 'Transfer'), ('wallet_topup', 'Wallet Top-up'), ('wallet_withdrawal', 'Wallet Withdrawal'), ('commission', 'Commission'), ('fee', 'Fee')], max_length=20),
        ),
    ]
