# Generated by Django 5.2.8 on 2026-01-12 16:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_merchandise_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='💰', help_text='Emoji or icon identifier for the category', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for category visualization', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Optional monthly budget limit for this category', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('momo_number', models.CharField(blank=True, help_text='Mobile Money number', max_length=20)),
                ('momo_provider', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('vodafone', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=50)),
                ('address', models.TextField(blank=True)),
                ('is_vendor', models.BooleanField(default=False, help_text='Is this recipient a vendor/supplier?')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Recipient',
                'verbose_name_plural': 'Expense Recipients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total money received from all successful transactions', max_digits=15)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total money spent on expenses', max_digits=15)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance (if there was existing money before system implementation)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Any notes about the balance')),
                ('currency', models.ForeignKey(default='GHS', on_delete=django.db.models.deletion.PROTECT, to='payments.currency')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balances',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(help_text='Brief title for the expense', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what the expense is for')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('recipient_name', models.CharField(blank=True, help_text='Recipient name if not using ExpenseRecipient model', max_length=255)),
                ('recipient_details', models.TextField(blank=True, help_text='Additional recipient details (account, phone, etc.)')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('momo', 'Mobile Money'), ('cheque', 'Cheque'), ('card', 'Card Payment'), ('petty_cash', 'Petty Cash')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank reference, MoMo ID, Cheque number, etc.', max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('receipt_url', models.URLField(blank=True, help_text='URL to receipt image if hosted externally')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs')),
                ('event_name', models.CharField(blank=True, help_text='Associated event or project name', max_length=255)),
                ('sms_notification_sent', models.BooleanField(default=False, editable=False)),
                ('sms_notification_error', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this expense')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected')),
                ('expense_date', models.DateField(help_text='Date when the expense occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Executive who approved this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Executive who recorded this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default='GHS', on_delete=django.db.models.deletion.PROTECT, to='payments.currency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.expensecategory')),
                ('recipient', models.ForeignKey(blank=True, help_text='Person or entity who received the money', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.expenserecipient')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Marked as Paid'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], max_length=20)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.expense')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Audit Log',
                'verbose_name_plural': 'Expense Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Budget name (e.g., 'Q1 2026 Event Budget')", max_length=255)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default='GHS', on_delete=django.db.models.deletion.PROTECT, to='payments.currency')),
                ('category', models.ForeignKey(blank=True, help_text='Category this budget applies to (leave empty for general budget)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='payments.expensecategory')),
            ],
            options={
                'verbose_name': 'Budget Allocation',
                'verbose_name_plural': 'Budget Allocations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'expense_date'], name='payments_ex_status_243252_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='payments_ex_categor_260ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by', 'status'], name='payments_ex_created_18275c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['reference'], name='payments_ex_referen_bba418_idx'),
        ),
    ]
