# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleader',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a profile photo', null=True, upload_to='HistoricalLeaders/'),
        ),
        migrations.AlterField(
            model_name='societyhistory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this historical record', null=True, upload_to='HistoryImages/'),
        ),
    ]
