# Generated by Django 5.1.10 on 2025-11-16 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Project title', max_length=255)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for cards', max_length=200)),
                ('student_names', models.TextField(help_text='Names of students who worked on this project (one per line)')),
                ('academic_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], help_text='Year project was completed', max_length=10)),
                ('level', models.CharField(default='Level 400', help_text='e.g., Level 100, Level 400, Masters', max_length=50)),
                ('category', models.CharField(choices=[('WEB', 'Web Development'), ('MOBILE', 'Mobile Development'), ('AI_ML', 'Artificial Intelligence & Machine Learning'), ('DATA_SCIENCE', 'Data Science & Analytics'), ('CYBERSECURITY', 'Cybersecurity'), ('IOT', 'Internet of Things'), ('GAME', 'Game Development'), ('BLOCKCHAIN', 'Blockchain'), ('CLOUD', 'Cloud Computing'), ('OTHER', 'Other')], help_text='Project category', max_length=50)),
                ('technologies', models.TextField(help_text='Technologies/tools used (comma-separated)')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('demo_url', models.URLField(blank=True, help_text='Live demo or video URL', null=True)),
                ('image', models.ImageField(help_text='Main project image/screenshot', upload_to='projects/')),
                ('image2', models.ImageField(blank=True, help_text='Additional image (optional)', null=True, upload_to='projects/')),
                ('image3', models.ImageField(blank=True, help_text='Additional image (optional)', null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this project on homepage/top')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide on public website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Project',
                'verbose_name_plural': 'Student Projects',
                'db_table': 'projects',
                'ordering': ['-is_featured', 'order', '-academic_year', '-created_at'],
            },
        ),
    ]
