# Generated by Django 5.1.10 on 2025-11-16 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='level',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student_names',
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Student full name', max_length=255)),
                ('level', models.CharField(choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('MASTERS', 'Masters'), ('PHD', 'PhD'), ('ALUMNI', 'Alumni')], help_text="Student's level during project", max_length=20)),
                ('program', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], default='CS', help_text='CS or IT program', max_length=10)),
                ('role', models.CharField(blank=True, help_text='Role in project (e.g., Team Lead, Backend Developer)', max_length=100)),
                ('student_id', models.CharField(blank=True, help_text='Student ID number (optional)', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Student email (optional)', max_length=254)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first, e.g., team lead first)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'db_table': 'project_members',
                'ordering': ['order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
