# Generated by Django 5.2.8 on 2025-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='level',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='year',
            field=models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('MASTERS', 'Masters'), ('PHD', 'PhD'), ('ALUMNI', 'Alumni')], default='4', help_text="Student's year during project", max_length=20),
        ),
    ]
