# Generated by Django 5.2.8 on 2025-12-31 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0017_alter_appointee_image_alter_executive_image'),
        ('projects', '0008_project_submitted_by_projectmember_is_submitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='update_approved_at',
            field=models.DateTimeField(blank=True, help_text='When the update request was approved', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='update_approved_by',
            field=models.ForeignKey(blank=True, help_text='Executive who approved the update request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_updates', to='executives.executive'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_request_reason',
            field=models.TextField(blank=True, help_text='Reason for requesting an update'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the update was requested', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='update_status',
            field=models.CharField(choices=[('none', 'No Update Requested'), ('pending', 'Update Requested'), ('approved', 'Update Approved'), ('in_progress', 'Update In Progress')], default='none', help_text='Status of update request for approved projects', max_length=20),
        ),
    ]
