# Generated by Django 5.2.2 on 2026-01-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_add_update_request_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_request_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for requesting an update'),
        ),
    ]
