# Generated by Django 5.2.8 on 2025-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for this product purchase', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='merchandise_taken_at',
            field=models.DateTimeField(blank=True, help_text='When merchandise was collected', null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of items purchased'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='taken_by',
            field=models.CharField(blank=True, help_text='Staff who verified collection', max_length=255, null=True),
        ),
    ]
