# Generated by Django 5.2.8 on 2025-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer full name', max_length=255, null=True),
        ),
    ]
