# Generated by Django 5.2.8 on 2025-12-13 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpayment_notification_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Color name (e.g., Black, Navy Blue)', max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Hex color code (e.g., #000000)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Available for selection')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Size name (e.g., Small, Medium, Large)', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Size code (e.g., S, M, L, XL)', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Available for selection')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(default=False, help_text='Does this product have color options?'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False, help_text='Does this product have size options?'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, help_text='Available colors for this product', related_name='products', to='products.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, help_text='Available sizes for this product', related_name='products', to='products.productsize'),
        ),
    ]
