# Generated by Django 5.2.8 on 2025-12-13 10:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_transaction_record_and_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='color_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload product image in this color', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL for this color instead of uploading', null=True),
        ),
    ]
