# Generated by Django 5.2.8 on 2025-12-13 11:47

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_color_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='color_image',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='color_image_url',
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color_image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload product image in this color', max_length=255, null=True)),
                ('color_image_url', models.URLField(blank=True, help_text='Alternative: Provide image URL for this color instead of uploading', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order for this color on the product')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Color Image',
                'verbose_name_plural': 'Product Color Images',
                'ordering': ['product', 'display_order'],
                'unique_together': {('product', 'color')},
            },
        ),
    ]
