# Generated by Django 5.2.8 on 2025-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_link_productpayments_to_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='academic_year',
            field=models.CharField(blank=True, editable=False, help_text="Academic year of purchase (e.g., '2025/2026'). Auto-calculated based on purchase date.", max_length=20),
        ),
    ]
