# Generated by Django 5.2.8 on 2025-12-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_productaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product price at the time of purchase (for price change tracking)', max_digits=10, null=True),
        ),
    ]
