# Generated by Django 5.2.8 on 2025-12-19 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_variant_selections_field'),
        ('products', '0030_productpayment_price_at_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpayment',
            name='transaction_record',
            field=models.ForeignKey(blank=True, help_text='Main transaction record - multiple ProductPayments can link to one Transaction (cart checkout)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_payments', to='payments.transaction'),
        ),
    ]
