# Generated by Django 5.2.8 on 2025-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_change_transaction_record_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='collection_details',
            field=models.JSONField(blank=True, default=list, help_text="\n        Per-variant collection tracking. Format:\n        [{\n            'variant_index': 0,\n            'color_id': 'uuid',\n            'size_id': 'uuid',\n            'ordered_quantity': 2,\n            'collected_quantity': 1,\n            'collected_at': '2025-12-19T10:30:00Z',\n            'collected_by': 'admin_username',\n            'substituted': false,\n            'substitution_notes': '',\n            'status': 'partial'  # 'pending', 'partial', 'collected', 'unavailable'\n        }]\n        "),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='merchandise_taken',
            field=models.BooleanField(default=False, help_text='Legacy: All items collected (True if all variants collected)'),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='merchandise_taken_at',
            field=models.DateTimeField(blank=True, help_text='When merchandise was collected (first collection timestamp)', null=True),
        ),
    ]
