# Generated by Django 5.2.2 on 2025-12-30 05:02

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='ProductImages/'),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='color_image',
            field=models.ImageField(blank=True, help_text='Upload product image in this color', null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='ProductColorImages/'),
        ),
    ]
