# Generated by Django 5.2.8 on 2026-01-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_programmes',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed programme codes (e.g., ['CS', 'IT']). Only applies if restrict_by_programme is True."),
        ),
        migrations.AddField(
            model_name='product',
            name='allowed_years',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed year numbers (e.g., [1, 2, 3, 4]). Only applies if restrict_by_year is True.'),
        ),
        migrations.AddField(
            model_name='product',
            name='eligibility_message',
            field=models.CharField(blank=True, help_text='Custom message explaining who can purchase (shown when user is not eligible)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='restrict_by_programme',
            field=models.BooleanField(default=False, help_text='Restrict this product to specific programmes'),
        ),
        migrations.AddField(
            model_name='product',
            name='restrict_by_year',
            field=models.BooleanField(default=False, help_text='Restrict this product to specific year groups'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Everyone (All Students)'), ('STAFF', 'Staff Only'), ('EXECUTIVES', 'Executives Only'), ('APPOINTEES', 'Appointees Only'), ('EXECUTIVES_AND_APPOINTEES', 'Executives and Appointees')], default='ALL', help_text='Who can purchase this product', max_length=30),
        ),
    ]
