# Generated by Django 5.2.8 on 2026-01-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_add_product_eligibility_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='preference_change_count',
            field=models.IntegerField(default=0, help_text='Number of times customer has changed their variant preferences (max 1 change allowed)'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='preferences_last_updated_at',
            field=models.DateTimeField(blank=True, help_text='When preferences were last updated', null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='preferences_locked',
            field=models.BooleanField(default=False, help_text='If True, preferences cannot be changed anymore (after collection or max changes)'),
        ),
    ]
