# Generated by Django 5.2.8 on 2026-01-07 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_merchandise_fields'),
        ('products', '0036_add_preference_change_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount saved due to discount (per unit)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='discount_applied',
            field=models.BooleanField(default=False, help_text='Whether a discount was applied to this purchase'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (if percentage discount)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='discount_reason',
            field=models.CharField(blank=True, help_text="Reason for discount (e.g., 'Executive discount')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='discount_type',
            field=models.CharField(blank=True, help_text="Type of discount: 'percentage' or 'fixed_price'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name for this discount (e.g., 'Executive Discount', 'Early Bird')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description explaining this discount')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED_PRICE', 'Fixed Price')], default='PERCENTAGE', help_text='Type of discount to apply', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (e.g., 15 for 15% off). Required if discount_type is PERCENTAGE.', max_digits=5, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for eligible users (e.g., 60.00 instead of 70.00). Required if discount_type is FIXED_PRICE.', max_digits=10, null=True)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('EXECUTIVES', 'Executives Only'), ('APPOINTEES', 'Appointees Only'), ('EXECUTIVES_AND_APPOINTEES', 'Executives and Appointees'), ('SPECIFIC_USERS', 'Specific Users'), ('STAFF', 'Staff Members')], default='EXECUTIVES_AND_APPOINTEES', help_text='Who qualifies for this discount', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Is this discount currently active?')),
                ('valid_from', models.DateTimeField(blank=True, help_text='When this discount becomes valid (leave empty for immediate)', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this discount expires (leave empty for no expiry)', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this discount can be used (leave empty for unlimited)', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this discount has been used')),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, help_text='Maximum uses per user (leave empty for unlimited)', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority discounts are applied first. If two discounts have same priority, the better one wins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product this discount applies to', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
                ('specific_users', models.ManyToManyField(blank=True, help_text='Specific users who qualify for this discount (only used when target_audience is SPECIFIC_USERS)', related_name='product_discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Discount',
                'verbose_name_plural': 'Product Discounts',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productpayment',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='The discount that was applied (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='products.productdiscount'),
        ),
        migrations.CreateModel(
            name='ProductDiscountUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='products.productdiscount')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Usage',
                'verbose_name_plural': 'Discount Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productdiscount',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_bc7e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='productdiscount',
            index=models.Index(fields=['target_audience', 'is_active'], name='products_pr_target__40b97c_idx'),
        ),
        migrations.AddIndex(
            model_name='productdiscount',
            index=models.Index(fields=['valid_from', 'valid_until'], name='products_pr_valid_f_c24a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='productdiscountusage',
            index=models.Index(fields=['discount', 'user'], name='products_pr_discoun_f9f12c_idx'),
        ),
        migrations.AddIndex(
            model_name='productdiscountusage',
            index=models.Index(fields=['used_at'], name='products_pr_used_at_e82528_idx'),
        ),
    ]
