# Generated by Django 5.2.8 on 2026-01-07 19:01

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_backfill_buyer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='is_purchase_on_behalf',
            field=models.BooleanField(default=False, help_text='True if buying on behalf of someone else (they requested it, more transactional)'),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='gift_linked_at',
            field=models.DateTimeField(blank=True, help_text='When this purchase was linked to the recipient user account', null=True),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='gift_message',
            field=models.TextField(blank=True, help_text='Optional gift message (only for gift purchases)', null=True),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='is_gift_purchase',
            field=models.BooleanField(default=False, help_text='True if this is a gift (with optional gift message, surprise element)'),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='purchased_for_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number of the person this product was purchased for', max_length=128, null=True, region=None),
        ),
    ]
