# Generated by Django 5.2.8 on 2025-12-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notifyuser_push_error_notifyuser_retry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyuser',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Use priority delivery (OTP type - faster but costs 0.035 extra per SMS)'),
        ),
    ]
