# Generated by Django 5.2.8 on 2025-12-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notifyuser_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyuser',
            name='email_error',
            field=models.TextField(blank=True, editable=False, help_text='Email error message if sending failed', null=True),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='email_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='notifyuser',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('email', 'Email'), ('both', 'SMS & Push Notification'), ('sms_email', 'SMS & Email'), ('push_email', 'Push & Email'), ('all', 'SMS, Push & Email')], default='sms', help_text='Choose how to send the notification', max_length=15),
        ),
        migrations.AlterField(
            model_name='notifyuser',
            name='title',
            field=models.CharField(blank=True, help_text='Notification title (used for push notifications and email subject)', max_length=100, null=True),
        ),
    ]
