# Generated by Django 5.2.8 on 2025-12-21 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_email_notification_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Internal name for this batch (e.g., 'Welcome Emails - Jan 2025')", max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('message', models.TextField(help_text='Email message content (plain text or will be wrapped in branded template)')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('email', 'Email'), ('both', 'SMS & Push Notification'), ('sms_email', 'SMS & Email'), ('push_email', 'Push & Email'), ('all', 'SMS, Push & Email')], default='email', help_text='Notification channel (only email-related channels are processed)', max_length=15)),
                ('filter_description', models.CharField(blank=True, help_text='Description of filter used to select recipients', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Batch',
                'verbose_name_plural': 'Email Batches',
                'db_table': 'email_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailBatchRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address used for this send', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.emailbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_batch_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Email Recipient',
                'verbose_name_plural': 'Batch Email Recipients',
                'db_table': 'email_batch_recipient',
                'ordering': ['id'],
                'unique_together': {('batch', 'user', 'email')},
            },
        ),
    ]
