# Generated by Django 5.2.8 on 2025-11-30 10:02

import django.db.models.deletion
import django_google_maps.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_academicslides_file_url_and_more'),
        ('timetable_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], max_length=10)),
                ('year', models.PositiveSmallIntegerField(help_text='Academic year (e.g., 1,2,3)')),
                ('group', models.CharField(choices=[('G1', 'Group 1'), ('G2', 'Group 2')], max_length=2)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=128, null=True)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
