# Generated by Django 5.2.8 on 2025-12-03 06:23

import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_system', '0004_make_academic_year_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='academic_year',
            field=models.CharField(choices=[('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031')], help_text='Academic year for this class schedule (e.g., 2025/2026)', max_length=9),
        ),
        migrations.AlterField(
            model_name='examinationschedule',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examinationschedule',
            name='room',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
