# Generated by Django 5.2.8 on 2026-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_system', '0005_alter_classschedule_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='group',
            field=models.CharField(blank=True, choices=[('G1', 'Group 1'), ('G2', 'Group 2')], help_text='Student group (G1/G2) - Required for Computer Science, optional for IT', max_length=2, null=True),
        ),
    ]
