# Generated by Django 5.2.8 on 2025-12-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_allow_anonymous_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='level',
        ),
        migrations.RemoveField(
            model_name='votingcategory',
            name='eligible_levels',
        ),
        migrations.RemoveField(
            model_name='votingevent',
            name='eligible_levels',
        ),
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year 1, 2, 3, or 4', null=True),
        ),
        migrations.AddField(
            model_name='votingcategory',
            name='eligible_years',
            field=models.JSONField(blank=True, default=list, help_text='Override event-level eligibility for this category: [1, 2, 3, 4]'),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='eligible_years',
            field=models.JSONField(blank=True, default=list, help_text='List of years that can vote: [1, 2, 3, 4]'),
        ),
    ]
