# Generated by Django 5.2.8 on 2025-12-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_candidate_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingevent',
            name='title',
            field=models.CharField(help_text="e.g., 'Year 2 Course Rep Elections 2024/2025'", max_length=200),
        ),
        migrations.AlterField(
            model_name='votingevent',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - All students can see'), ('year', 'Year Specific - Only specific years'), ('program', 'Program Specific - Only specific programs'), ('private', 'Private - Invited users only')], default='public', max_length=20),
        ),
    ]
