# Generated by Django 5.2.8 on 2025-12-28 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_add_registration_voting_open_switches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of device fingerprint for anonymous vote tracking', max_length=64),
        ),
        migrations.AddField(
            model_name='vote',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Session ID for tracking anonymous voters', max_length=64),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='requires_authentication',
            field=models.BooleanField(default=True, help_text='Require users to login to vote? If False, anonymous voting is allowed for public events.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['event', 'device_fingerprint'], name='voting_vote_event_i_89322b_idx'),
        ),
    ]
