# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_alter_vote_candidate_polloption_vote_poll_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='CandidateProfiles/'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PollOptions/'),
        ),
        migrations.AlterField(
            model_name='votingevent',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='VotingBanners/'),
        ),
    ]
