# Generated by Django 5.1.10 on 2025-07-01 19:42

import cloudinary.models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("product_image", cloudinary.models.CloudinaryField(max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "type_of_product",
                    models.CharField(
                        choices=[
                            ("cloth", "cloth"),
                            ("books", "books"),
                            ("utilities", "utilities"),
                        ],
                        max_length=255,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductPayment",
            fields=[
                (
                    "payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "transaction_validation_code",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("transaction", models.CharField(max_length=50)),
                (
                    "payed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Payed"),
                ),
                ("payment_successful", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Payment",
                "verbose_name_plural": "Product Payments",
                "db_table": "product_payment",
            },
        ),
    ]
