# Generated by Django 5.1.10 on 2025-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpayment",
            name="merchandise_taken",
            field=models.BooleanField(default=False),
        ),
    ]
