# Generated by Django 5.1.10 on 2025-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productpayment_merchandise_taken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/hide product on website'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Alert when stock goes below this number'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_end_date',
            field=models.DateTimeField(blank=True, help_text='When sales end (leave empty for no end date)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_start_date',
            field=models.DateTimeField(blank=True, help_text='When sales begin (leave empty for immediate availability)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available for Sale'), ('OUT_OF_STOCK', 'Out of Stock'), ('COMING_SOON', 'Coming Soon'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', help_text='Product availability status', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Available quantity in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('cloth', 'cloth'), ('books', 'books'), ('utilities', 'utilities'), ('tickets', 'tickets')], max_length=255),
        ),
    ]
