# Generated by Django 5.2.8 on 2025-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productpayment_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='notification_error',
            field=models.TextField(blank=True, editable=False, help_text='Notification error details if sending failed', null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='notification_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Whether any notification was sent'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='push_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Whether push notification was sent'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='sms_campaign_id',
            field=models.CharField(blank=True, editable=False, help_text='MNotify SMS campaign ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='sms_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Whether SMS notification was sent'),
        ),
    ]
