# Generated by Django 5.2.8 on 2025-12-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_variant_selections_field'),
        ('products', '0008_productcolor_productsize_product_has_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='transaction_record',
            field=models.OneToOneField(blank=True, help_text='Main transaction record (financial data) - use this for new payments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_payment', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='variant_selections',
            field=models.JSONField(blank=True, default=list, help_text="Customer's color/size preferences. Format: [{'color_id': 'uuid', 'size_id': 'uuid', 'quantity': 1}]"),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='transaction',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
