# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_add_collection_details_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages/'),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='color_image',
            field=models.ImageField(blank=True, help_text='Upload product image in this color', null=True, upload_to='ProductColorImages/'),
        ),
    ]
