# Generated by Django 5.2.8 on 2026-01-07 17:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_add_product_discount_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='The user who actually paid for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='gift_linked_at',
            field=models.DateTimeField(blank=True, help_text='When this gift purchase was linked to the recipient user account', null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='gift_message',
            field=models.TextField(blank=True, help_text='Optional gift message from buyer to recipient', null=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='is_gift_purchase',
            field=models.BooleanField(default=False, help_text='If True, this purchase was made on behalf of someone else'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='purchased_for_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number of the person this product was purchased for (if gift purchase)', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='purchased_for_user',
            field=models.ForeignKey(blank=True, help_text='The user this product was purchased for (auto-linked when user with phone registers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
