# Generated by Django 5.2.8 on 2026-01-13 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_add_purchase_on_behalf_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available quantity for this specific variant')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock goes below this number')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Quantity reserved in active carts (not yet purchased)')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit for this variant (e.g., TSHIRT-BLK-M)', max_length=100)),
                ('last_restocked_at', models.DateTimeField(blank=True, help_text='When this variant was last restocked', null=True)),
                ('restock_quantity', models.IntegerField(default=0, help_text='Quantity added in last restock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, help_text='Color for this variant (null if product has no colors)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='products.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='products.product')),
                ('size', models.ForeignKey(blank=True, help_text='Size for this variant (null if product has no sizes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='products.productsize')),
            ],
            options={
                'verbose_name': 'Product Variant Stock',
                'verbose_name_plural': 'Product Variant Stocks',
                'db_table': 'product_variant_stock',
                'ordering': ['product', 'color', 'size'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantStockAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('restock', 'Restocked'), ('sale', 'Sold'), ('reserved', 'Reserved'), ('released', 'Released Reservation'), ('adjustment', 'Manual Adjustment'), ('returned', 'Returned'), ('damaged', 'Marked as Damaged'), ('initial', 'Initial Stock')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for additions, negative for reductions')),
                ('quantity_after', models.IntegerField(help_text='Stock quantity after this change')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audits', to='products.productpayment')),
                ('variant_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.productvariantstock')),
            ],
            options={
                'verbose_name': 'Variant Stock Audit',
                'verbose_name_plural': 'Variant Stock Audits',
                'db_table': 'product_variant_stock_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productvariantstock',
            index=models.Index(fields=['product', 'stock_quantity'], name='product_var_product_473893_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantstock',
            index=models.Index(fields=['color', 'stock_quantity'], name='product_var_color_i_d6c2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantstock',
            index=models.Index(fields=['size', 'stock_quantity'], name='product_var_size_id_d05326_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantstock',
            unique_together={('product', 'color', 'size')},
        ),
    ]
