# Generated by Django 5.2.8 on 2025-12-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donationwithdrawal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='show_amount',
        ),
    ]
