# Generated by Django 5.1.10 on 2025-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="media_link",
            field=models.URLField(
                help_text="Url for more pictures and videos taken at the event",
                null=True,
            ),
        ),
    ]
