# Generated by Django 5.1.10 on 2025-11-18 06:13

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_end_date_alter_event_event_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlist', 'Waitlist')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('year_group', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=200, null=True)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('maybe', 'Maybe'), ('not_attending', 'Not Attending')], max_length=20)),
                ('reminder', models.CharField(choices=[('none', 'No Reminder'), ('1_hour', '1 Hour Before'), ('1_day', '1 Day Before'), ('1_week', '1 Week Before')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="User's notes about attendance", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event RSVP',
                'verbose_name_plural': 'Event RSVPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncMemoAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended'), ('archived', 'Archived')], default='live', max_length=20)),
                ('cover_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('allow_uploads', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False, help_text='Photos require admin approval before being visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Memo Album',
                'verbose_name_plural': 'Sync Memo Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncMemoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo Comment',
                'verbose_name_plural': 'Photo Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncMemoCommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncMemoLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo Like',
                'verbose_name_plural': 'Photo Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncMemoPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('share_to_feed', models.BooleanField(default=False, help_text='Share this photo to the news feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Memo Photo',
                'verbose_name_plural': 'Sync Memo Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('year_group', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, help_text='Role in team', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='allows_rsvp',
            field=models.BooleanField(default=True, help_text='Allow users to RSVP to this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='allows_team_registration',
            field=models.BooleanField(default=False, help_text='Allow team registrations (for competitions/hackathons)'),
        ),
        migrations.AddField(
            model_name='event',
            name='building',
            field=models.CharField(blank=True, help_text="Building name (e.g., 'New Block')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='emoji',
            field=models.CharField(blank=True, help_text='Emoji icon for event (e.g., 🎓, 🚀, 💻)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('meeting', 'Meeting'), ('competition', 'Competition'), ('social', 'Social'), ('talk', 'Tech Talk'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('other', 'Other')], default='other', help_text='Category of event for mobile app filtering', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this event in mobile app'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('physical', 'Physical Location'), ('virtual', 'Virtual Event'), ('hybrid', 'Hybrid Event')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.IntegerField(blank=True, help_text='Maximum number of attendees (null = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='event',
            name='min_team_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for registration', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_registration',
            field=models.BooleanField(default=False, help_text='Does this event require registration? (Different from external registration_link)'),
        ),
        migrations.AddField(
            model_name='event',
            name='sync_memo_enabled',
            field=models.BooleanField(default=True, help_text='Enable photo uploads for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, help_text="Physical venue name (e.g., 'NB LT1')", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_link',
            field=models.URLField(blank=True, help_text='Virtual meeting link (Google Meet, Zoom, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Registration link for event if any (external registration)', null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date', '-created_at'], name='events_even_event_d_71b904_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'event_date'], name='events_even_event_t_e0bb81_idx'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncmemoalbum',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_memo_album', to='events.event'),
        ),
        migrations.AddField(
            model_name='syncmemocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_memo_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncmemocommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='events.syncmemocomment'),
        ),
        migrations.AddField(
            model_name='syncmemocommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncmemolike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_memo_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncmemophoto',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.syncmemoalbum'),
        ),
        migrations.AddField(
            model_name='syncmemophoto',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncmemophoto',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_memo_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncmemolike',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='events.syncmemophoto'),
        ),
        migrations.AddField(
            model_name='syncmemocomment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.syncmemophoto'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='events.eventregistration'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_cdd3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', '-created_at'], name='events_even_user_id_7ff8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['team_name'], name='events_even_team_na_c95f08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_c5a858_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['user', '-created_at'], name='events_even_user_id_9d1575_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='syncmemocommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='syncmemophoto',
            index=models.Index(fields=['album', '-created_at'], name='events_sync_album_i_6e1830_idx'),
        ),
        migrations.AddIndex(
            model_name='syncmemophoto',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='events_sync_uploade_a0431d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncmemolike',
            unique_together={('photo', 'user')},
        ),
        migrations.AddIndex(
            model_name='syncmemocomment',
            index=models.Index(fields=['photo', 'created_at'], name='events_sync_photo_i_3e7267_idx'),
        ),
    ]
