# Generated by Django 5.1.10 on 2025-11-19 10:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration_eventrsvp_syncmemoalbum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image_1_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image_2_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='syncmemoalbum',
            name='cover_photo_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide cover photo URL instead of uploading', null=True),
        ),
        migrations.AddField(
            model_name='syncmemophoto',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide photo URL instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='syncmemophoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
