# Generated by Django 5.2.2 on 2025-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_image_1_url_event_event_image_2_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='EventsImages/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='EventsImages/'),
        ),
        migrations.AlterField(
            model_name='syncmemoalbum',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='SyncMemo/Covers/'),
        ),
        migrations.AlterField(
            model_name='syncmemophoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='SyncMemo/Photos/'),
        ),
    ]
