# Generated by Django 5.2.2 on 2025-12-30 05:02

import utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_event_image_1_alter_event_event_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image_1',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='EventsImages/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image_2',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='EventsImages/'),
        ),
        migrations.AlterField(
            model_name='syncmemoalbum',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='SyncMemo/Covers/'),
        ),
        migrations.AlterField(
            model_name='syncmemophoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=utils.dynamic_storage.DynamicStorage(), upload_to='SyncMemo/Photos/'),
        ),
    ]
