# Generated by Django 5.2.8 on 2026-01-24 13:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_image_1_alter_event_event_image_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPaymentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Package name (e.g., 'Standard Ticket', 'VIP Access')", max_length=100)),
                ('package_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('student', 'Student'), ('group', 'Group'), ('early_bird', 'Early Bird'), ('late', 'Late Registration'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True, help_text="What's included in this package", null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular price in GHS', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, help_text="Early bird price (uses event's early_bird_deadline)", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_slots', models.IntegerField(blank=True, help_text='Maximum slots for this package (null = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of benefits included in this package')),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, help_text='When this package becomes available', null=True)),
                ('available_until', models.DateTimeField(blank=True, help_text='When this package expires', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which packages are displayed (lower = first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this package as recommended')),
                ('badge_text', models.CharField(blank=True, help_text="Badge text to display (e.g., 'Most Popular', 'Best Value')", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Payment Package',
                'verbose_name_plural': 'Event Payment Packages',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='EventPaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to refund', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(choices=[('event_cancelled', 'Event Cancelled'), ('user_request', 'User Request'), ('duplicate_payment', 'Duplicate Payment'), ('event_rescheduled', 'Event Rescheduled'), ('dissatisfaction', 'User Dissatisfaction'), ('admin_decision', 'Admin Decision'), ('other', 'Other')], max_length=30)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details about refund reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Payment Refund',
                'verbose_name_plural': 'Event Payment Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Unique transaction reference', max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('partial_payment', 'Partial Payment'), ('balance_payment', 'Balance Payment'), ('refund', 'Refund')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Card Payment'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('cash', 'Cash'), ('manual', 'Manual Payment')], max_length=20)),
                ('payment_gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('momo', 'Mobile Money Direct'), ('manual', 'Manual/Cash')], default='paystack', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Detailed status message or error')),
                ('gateway_reference', models.CharField(blank=True, db_index=True, help_text='Reference from payment gateway', max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full response from payment gateway')),
                ('authorization_url', models.URLField(blank=True, help_text='URL for payment authorization (for redirect-based payments)', null=True)),
                ('access_code', models.CharField(blank=True, help_text='Access code for payment (Paystack)', max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged by payment gateway', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount after gateway fees', max_digits=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded', max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this payment session expires', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False, help_text='Has this transaction been verified with gateway')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Payment Transaction',
                'verbose_name_plural': 'Event Payment Transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='allow_partial_payment',
            field=models.BooleanField(default=False, help_text='Allow users to pay in installments'),
        ),
        migrations.AddField(
            model_name='event',
            name='early_bird_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for early bird pricing (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='minimum_deposit_percentage',
            field=models.IntegerField(default=50, help_text='Minimum deposit percentage if partial payment is allowed', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for payment. After this, registration closes.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_description',
            field=models.TextField(blank=True, help_text="Description of what the payment covers (e.g., 'Includes lunch, materials, and certificate')", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_payment',
            field=models.BooleanField(default=False, help_text='Does this event require payment for registration?'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount due for registration', max_digits=10),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, help_text='When payment was fully completed', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Payment Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded'), ('failed', 'Payment Failed')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Unique registration number for tracking', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlist', 'Waitlist'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['requires_payment', 'event_date'], name='events_even_require_322d9f_idx'),
        ),
        migrations.AddField(
            model_name='eventpaymentpackage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_packages', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_package',
            field=models.ForeignKey(blank=True, help_text='Selected payment package for this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.eventpaymentpackage'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'payment_status'], name='events_even_event_i_11380a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['registration_number'], name='events_even_registr_f8e3b1_idx'),
        ),
        migrations.AddField(
            model_name='eventpaymentrefund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_event_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpaymentrefund',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_event_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpaymentrefund',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='eventpaymenttransaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventpaymenttransaction',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='events.eventpaymentpackage'),
        ),
        migrations.AddField(
            model_name='eventpaymenttransaction',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_refunds_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpaymenttransaction',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='eventpaymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpaymentrefund',
            name='original_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='events.eventpaymenttransaction'),
        ),
        migrations.AddIndex(
            model_name='eventpaymentpackage',
            index=models.Index(fields=['event', 'is_active'], name='events_even_event_i_06eff4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymentpackage',
            index=models.Index(fields=['event', 'display_order'], name='events_even_event_i_371182_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymenttransaction',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_463242_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymenttransaction',
            index=models.Index(fields=['registration', 'status'], name='events_even_registr_a62edf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymenttransaction',
            index=models.Index(fields=['user', '-initiated_at'], name='events_even_user_id_a64226_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymenttransaction',
            index=models.Index(fields=['reference'], name='events_even_referen_35bd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymenttransaction',
            index=models.Index(fields=['gateway_reference'], name='events_even_gateway_c58d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymenttransaction',
            index=models.Index(fields=['status', '-initiated_at'], name='events_even_status_bbd2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymentrefund',
            index=models.Index(fields=['original_transaction', 'status'], name='events_even_origina_72a875_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpaymentrefund',
            index=models.Index(fields=['registration', 'status'], name='events_even_registr_125a37_idx'),
        ),
    ]
