# Generated by Django 5.1.10 on 2025-11-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyuser',
            name='action',
            field=models.CharField(choices=[('send', 'send'), ('draft', 'draft'), ('sent', 'sent')], default='draft', max_length=255),
        ),
    ]
