# Generated by Django 5.2.8 on 2025-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notifyuser_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyuser',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('both', 'SMS & Push Notification')], default='sms', help_text='Choose how to send the notification', max_length=10),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='push_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for push notification (e.g., screen to navigate to)'),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='push_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='sms_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='title',
            field=models.CharField(blank=True, help_text='Notification title (used for push notifications)', max_length=100, null=True),
        ),
    ]
