# Generated by Django 5.2.8 on 2025-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notifyuser_channel_notifyuser_push_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyuser',
            name='push_error',
            field=models.TextField(blank=True, editable=False, help_text='Push notification error message if sending failed', null=True),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='retry_count',
            field=models.IntegerField(default=0, editable=False, help_text='Number of send attempts'),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='sms_campaign_id',
            field=models.CharField(blank=True, editable=False, help_text='MNotify campaign ID for tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notifyuser',
            name='sms_error',
            field=models.TextField(blank=True, editable=False, help_text='SMS error message if sending failed', null=True),
        ),
    ]
