# Generated by Django 5.2.8 on 2025-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailbatch_emailbatchrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbatch',
            name='message',
            field=models.TextField(help_text='Email message content. Available placeholders: {name}, {full_name}, {phone}, {student_id}, {index_number}, {personal_email}, {student_email}, {program}, {program_full}, {group}, {level}, {year}, {semester}, {graduation_year}, {gender}'),
        ),
        migrations.AlterField(
            model_name='notifyuser',
            name='message',
            field=models.TextField(help_text='Message for the user. Available placeholders: {name}, {full_name}, {phone}, {student_id}, {index_number}, {personal_email}, {student_email}, {program}, {program_full}, {group}, {level}, {year}, {semester}, {graduation_year}, {gender}'),
        ),
    ]
