# Generated by Django 5.2.8 on 2025-11-30 10:00

import django.db.models.deletion
import django_google_maps.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_academicslides_file_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_number_start', models.CharField(default=0, help_text='Starting index number for that particular room', max_length=230)),
                ('index_number_end', models.CharField(default=0, help_text='Last index number for that particular room', max_length=230)),
                ('time', models.DateTimeField(null=True)),
                ('college', models.CharField(help_text='The college where the exam is suppose to take place', max_length=255)),
                ('room', models.CharField(max_length=230, null=True)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('message_schedule', models.DateTimeField(blank=True, help_text='The time a message is suppose to be sent all students who have this exam; If no time is set the system will send message 1 hour before the paper', null=True)),
                ('action', models.CharField(choices=[('hold_scheduling', 'Hold Scheduling'), ('schedule_message', 'Schedule Message')], default='hold_scheduling', help_text='Schedule Message Should Only Be Selected When Every Detail Of The Examination Like Time And Location Is Confirm', max_length=255)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
            options={
                'verbose_name': 'Examination Schedule Per Class',
                'verbose_name_plural': 'Examination Schedules',
            },
        ),
    ]
