# Generated by Django 5.2.8 on 2025-11-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_system', '0002_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031')], help_text='Academic year for this class schedule (e.g., 2025/2026)', max_length=9, null=True),
        ),
    ]
