# Generated by Django 5.2.8 on 2025-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverifcationcodes',
            name='last_sent',
            field=models.DateTimeField(blank=True, editable=False, help_text='Track when SMS was last sent to prevent spam', null=True),
        ),
        migrations.AddField(
            model_name='phoneverifcationcodes',
            name='send_count',
            field=models.IntegerField(default=0, help_text='Number of times SMS has been sent for this code'),
        ),
    ]
