# Generated by Django 5.2.8 on 2025-12-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, choices=[('G1', 'Group 1'), ('G2', 'Group 2')], help_text='The group/section the student belongs to for timetabling', max_length=2, null=True),
        ),
    ]
