# Generated by Django 5.2.8 on 2025-12-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userdevice_block_reason_userdevice_blocked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Optional middle name', max_length=255, null=True),
        ),
    ]
