# Generated by Django 5.2.8 on 2026-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_required_from_level_to_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, choices=[('G1', 'Group 1'), ('G2', 'Group 2')], help_text='The group/section the student belongs to (G1/G2). Currently only required for Computer Science students. IT students do not have groups.', max_length=2, null=True),
        ),
    ]
