# Generated by Django 5.2.8 on 2026-01-18 16:40

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Home', help_text='Label for this address (e.g., Home, Office, Campus)', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, etc.', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, etc.', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, help_text='State/Province/Region', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('digital_address', models.CharField(blank=True, help_text='Ghana Post GPS digital address (e.g., GA-123-4567)', max_length=50)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark to help locate the address', max_length=255)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special instructions for delivery')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default shipping address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'db_table': 'user_shipping_addresses',
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='user_shippi_user_id_5cdf66_idx')],
            },
        ),
    ]
