# Generated by Django 5.2.8 on 2026-02-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_shipping_address_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverifcationcodes',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for code delivery as fallback', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phoneverifcationcodes',
            name='email_send_count',
            field=models.IntegerField(default=0, help_text='Number of times email has been sent for this code'),
        ),
        migrations.AddField(
            model_name='phoneverifcationcodes',
            name='last_delivery_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', help_text='The last method used to deliver the code', max_length=10),
        ),
        migrations.AddField(
            model_name='phoneverifcationcodes',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, editable=False, help_text='Track when email was last sent', null=True),
        ),
    ]
