# Generated by Django 5.1.10 on 2025-11-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.CharField(blank=True, choices=[('CS', 'BSc Computer Science'), ('IT', 'BSc Information Technology')], help_text='The program the student is enrolled in', max_length=2, null=True),
        ),
    ]
