# Generated by Django 5.2.8 on 2025-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneverifcationcodes_last_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_semester',
            field=models.IntegerField(blank=True, help_text='Current semester (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='index_number',
            field=models.CharField(blank=True, help_text='Student index number (may not be available immediately)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_email',
            field=models.EmailField(blank=True, help_text='Official student email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, help_text='Unique student identifier', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FieldRequirementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('student_id', 'Student ID'), ('index_number', 'Index Number'), ('personal_email', 'Personal Email'), ('student_email', 'Student Email'), ('gender', 'Gender'), ('program', 'Program'), ('first_name', 'First Name'), ('last_name', 'Last Name'), ('phone', 'Phone'), ('graduation_year', 'Graduation Year')], help_text='Name of the field this configuration applies to', max_length=100)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is required')),
                ('required_from_level', models.IntegerField(blank=True, help_text='Level from which this field becomes required (e.g., 200, 300)', null=True)),
                ('description', models.TextField(help_text='Description of when/why this field is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Requirement Configuration',
                'verbose_name_plural': 'Field Requirement Configurations',
                'db_table': 'field_requirement_config',
                'ordering': ['required_from_level', 'field_name'],
                'unique_together': {('field_name', 'required_from_level')},
            },
        ),
    ]
