# Generated by Django 5.2.8 on 2025-12-10 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile Device'), ('tablet', 'Tablet'), ('desktop', 'Desktop/Laptop'), ('web', 'Web Browser'), ('unknown', 'Unknown')], default='unknown', help_text='Type of device (mobile, tablet, desktop, web)', max_length=20)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('web', 'Web Browser'), ('unknown', 'Unknown')], default='unknown', help_text='Operating system or platform', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='Device model or name (e.g., iPhone 15, Samsung Galaxy S23)', max_length=255, null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current active device?')),
                ('last_active', models.DateTimeField(auto_now=True, help_text='Last time this device was active')),
                ('first_login', models.DateTimeField(auto_now_add=True, help_text='First time this device logged in')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the device', null=True)),
                ('country', models.CharField(blank=True, help_text='Country from IP geolocation', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City from IP geolocation', max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Full user agent string', null=True)),
                ('device_fingerprint', models.CharField(blank=True, help_text='Unique identifier for this device', max_length=255, null=True)),
                ('refresh_token_jti', models.CharField(blank=True, help_text='JWT refresh token JTI for session management', max_length=255, null=True)),
                ('is_trusted', models.BooleanField(default=False, help_text='Has user marked this device as trusted?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this session still active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True, help_text='Was the login successful?')),
                ('reason', models.CharField(blank=True, help_text='Reason for failed login (if applicable)', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='accounts.userdevice')),
            ],
            options={
                'verbose_name': 'Device Login History',
                'verbose_name_plural': 'Device Login Histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', '-last_active'], name='accounts_us_user_id_0f1fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_054818_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_fingerprint'], name='accounts_us_device__f36a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceloginhistory',
            index=models.Index(fields=['user', '-login_time'], name='accounts_de_user_id_ab3476_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceloginhistory',
            index=models.Index(fields=['device', '-login_time'], name='accounts_de_device__9f0d08_idx'),
        ),
    ]
