# Generated by Django 5.2.8 on 2025-12-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdevice_deviceloginhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='block_reason',
            field=models.CharField(blank=True, help_text='Reason for blocking this device', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='When was this device blocked?', null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Is this device blocked from accessing the account?'),
        ),
    ]
