# Generated by Django 5.2.8 on 2025-12-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_middle_name'),
    ]

    operations = [
        # First, remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name='fieldrequirementconfig',
            unique_together=set(),
        ),
        # Rename the field
        migrations.RenameField(
            model_name='fieldrequirementconfig',
            old_name='required_from_level',
            new_name='required_from_year',
        ),
        # Update help_text
        migrations.AlterField(
            model_name='fieldrequirementconfig',
            name='required_from_year',
            field=models.IntegerField(blank=True, help_text='Year from which this field becomes required (e.g., 2, 3, 4)', null=True),
        ),
        # Add new unique_together constraint with renamed field
        migrations.AlterUniqueTogether(
            name='fieldrequirementconfig',
            unique_together={('field_name', 'required_from_year')},
        ),
        # Update ordering
        migrations.AlterModelOptions(
            name='fieldrequirementconfig',
            options={'ordering': ['required_from_year', 'field_name'], 'verbose_name': 'Field Requirement Configuration', 'verbose_name_plural': 'Field Requirement Configurations'},
        ),
    ]
