# Generated by Django 5.1.10 on 2025-11-12 10:25

from django.db import migrations


def seed_categories(apps, schema_editor):
    """Populate HelpDesk categories"""
    HelpDeskCategory = apps.get_model('helpdesk', 'HelpDeskCategory')
    
    categories = [
        {
            'id': 'academic',
            'name': 'Academic Help',
            'emoji': '🎓',
            'icon': 'school',
            'description': 'Course concepts, assignments, exam prep',
            'display_order': 1,
            'is_active': True,
        },
        {
            'id': 'technical',
            'name': 'Technical Support',
            'emoji': '💻',
            'icon': 'code-slash',
            'description': 'Programming, tools, software, debugging',
            'display_order': 2,
            'is_active': True,
        },
        {
            'id': 'society',
            'name': 'Society & Events',
            'emoji': '🎉',
            'icon': 'people',
            'description': 'CSS activities, events, meetings',
            'display_order': 3,
            'is_active': True,
        },
        {
            'id': 'codequest',
            'name': 'CodeQuest Support',
            'emoji': '🏆',
            'icon': 'trophy',
            'description': 'CodeQuest competition help',
            'display_order': 4,
            'is_active': True,
        },
        {
            'id': 'career',
            'name': 'Career & Internships',
            'emoji': '💼',
            'icon': 'briefcase',
            'description': 'Career advice, internships, job prep',
            'display_order': 5,
            'is_active': True,
        },
        {
            'id': 'general',
            'name': 'General Help',
            'emoji': '❓',
            'icon': 'help-circle',
            'description': 'Other questions and requests',
            'display_order': 6,
            'is_active': True,
        },
    ]
    
    for cat_data in categories:
        HelpDeskCategory.objects.get_or_create(
            id=cat_data['id'],
            defaults=cat_data
        )


def reverse_seed_categories(apps, schema_editor):
    """Remove seeded categories"""
    HelpDeskCategory = apps.get_model('helpdesk', 'HelpDeskCategory')
    HelpDeskCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed_categories),
    ]

