"""
Django settings for BioChemSystem project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from BioChemSystem.config import *
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "cloudinary",
    "django_filters",
    "drf_spectacular",
    "accounts",
    "core",
    "products",
    "timeline",
    "events",
    "codequest",  # Code Quest Management System
    "executives",
    "history",  # Society History Management
    "academics",
    "news",
    "phonenumber_field",
    "advertisements",
    "django_google_maps",
    "timetable_system",
    "helpdesk",
    "planner",
    "faculty",
    "projects",
    "voting",  # Advanced Voting & Elections System
    "payments",  # Universal Payment & Transaction System
    "notifications",  # Push Notification System
    "admissions",  # KNUST Admission Eligibility & Guidance System
    "mentorship",  # Mentorship System
    "donations",  # Public Donation System
    "calendar_sync",  # Phone Calendar Synchronization System
    "el_mercado",  # El Mercado - Multi-Vendor Marketplace Platform (B2C & P2P)
]

MIDDLEWARE = [
    "BioChemSystem.middleware.PerformanceMiddleware",  # Monitor request performance
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.device_middleware.BlockedDeviceMiddleware",  # Check for blocked devices
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "BioChemSystem.middleware.SafeErrorHandlerMiddleware",  # Catch unhandled errors
    "BioChemSystem.middleware.DatabaseConnectionMiddleware",  # Clean DB connections
]

# CORS settings
if DEBUG:
    # Development settings
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",  # React default port
        "http://localhost:5173",  # Vite default port
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://172.20.10.2:8081",
        FRONTEND_URL,
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://172.20.10.2:8081",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        FRONTEND_URL,
    ]
else:
    # Production settings
    CORS_ALLOWED_ORIGINS = [
        FRONTEND_URL,
    ]
    CSRF_TRUSTED_ORIGINS = [
        FRONTEND_URL,
    ]

# Additional CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "contact_us": "10/day",
        "signup": "10/hour",  # Updated: 10 signups per hour per phone number
        "login": "20/hour",  # Updated: 20 logins per hour per phone number
    },
}


ROOT_URLCONF = "BioChemSystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "BioChemSystem.context_processors.google_maps_api_key",
                "BioChemSystem.context_processors.brand_context",
            ],
        },
    },
]

WSGI_APPLICATION = "BioChemSystem.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "biochem_db.sqlite3",
    }
}


SPECTACULAR_SETTINGS = {
    "TITLE": f"{BRAND_NAME} Backend System",
    "DESCRIPTION": f"{BRAND_NAME} Backend System APIs",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # OTHER SETTINGS
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication backends
# Custom backend to normalize phone numbers during login
AUTHENTICATION_BACKENDS = [
    'accounts.backends.PhoneNumberAuthBackend',  # Custom backend with phone normalization
    'django.contrib.auth.backends.ModelBackend',  # Fallback to default
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "accounts.CustomUser"


# MEDIA_ROOT = ROOT_DIR / "media"

# MEDIA_URL = "/media/"

# DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.RawMediaCloudinaryStorage"
# DISABLED: Cloudinary storage - using local storage now
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=False)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

# Paystack Payment Gateway Configuration
PAYSTACK_PUBLIC_KEY = config("PAYSTACK_PUBLIC_KEY")
PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY")

# Google Maps API Configuration
GOOGLE_MAPS_API_KEY = config("GOOGLE_MAPS_API_KEY", default="")

# ===========================
# CELERY CONFIGURATION
# ===========================
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery Beat Schedule for periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Process scheduled notifications every 5 minutes
    'process-scheduled-notifications': {
        'task': 'notifications.tasks.process_scheduled_notifications',
        'schedule': 300.0,  # 5 minutes in seconds
    },
    # Generate class schedule notifications every 6 hours
    'generate-class-notifications': {
        'task': 'notifications.tasks.generate_class_schedule_notifications',
        'schedule': crontab(minute=0, hour='*/6'),  # Every 6 hours
    },
    # Generate exam notifications daily at 8 AM
    'generate-exam-notifications': {
        'task': 'notifications.tasks.generate_exam_schedule_notifications',
        'schedule': crontab(minute=0, hour=8),  # Daily at 8 AM
    },
    # Cleanup old notifications weekly on Sunday at 2 AM
    'cleanup-old-notifications': {
        'task': 'notifications.tasks.cleanup_old_notifications',
        'schedule': crontab(minute=0, hour=2, day_of_week=0),  # Sunday at 2 AM
    },
    
    # ======================================
    # CALENDAR REMINDER TASKS (Push Notifications)
    # ======================================
    # Process and send pending calendar reminders every 2 minutes
    'process-calendar-reminders': {
        'task': 'calendar_sync.tasks.process_calendar_reminders',
        'schedule': 120.0,  # Every 2 minutes
    },
    # Schedule class reminders every 4 hours
    'schedule-class-reminders': {
        'task': 'calendar_sync.tasks.schedule_class_reminders',
        'schedule': crontab(minute=0, hour='*/4'),  # Every 4 hours
    },
    # Schedule exam reminders daily at 6 AM
    'schedule-exam-reminders': {
        'task': 'calendar_sync.tasks.schedule_exam_reminders',
        'schedule': crontab(minute=0, hour=6),  # Daily at 6 AM
    },
    # Schedule event reminders daily at 6:30 AM
    'schedule-event-reminders': {
        'task': 'calendar_sync.tasks.schedule_event_reminders',
        'schedule': crontab(minute=30, hour=6),  # Daily at 6:30 AM
    },
    # Cleanup old calendar reminders daily at 3 AM
    'cleanup-calendar-reminders': {
        'task': 'calendar_sync.tasks.cleanup_old_reminders',
        'schedule': crontab(minute=0, hour=3),  # Daily at 3 AM
    },
}

# ===========================
# LOGGING CONFIGURATION
# ===========================
# PRODUCTION-READY CONFIGURATION FOR PYTHONANYWHERE
# All logs go to files only - NO CONSOLE OUTPUT
# This prevents OSError: write error on PythonAnywhere
import os

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module}.{funcName}:{lineno} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # Main application log - INFO and above
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Error log - ERROR and CRITICAL only
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        # Debug log - only in DEBUG mode
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'debug.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'detailed',
            'filters': ['require_debug_true'],
            'encoding': 'utf-8',
        },
        # SMS/Communication logs
        'sms_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'sms.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Email logs
        'email_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'email.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Payment transaction logs
        'payment_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'payments.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        # API/Request logs
        'api_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'api.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Celery/Background task logs
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'celery.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Scraper/Automation logs
        'automation_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'automation.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Security/Auth logs
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        # Null handler for disabling specific loggers
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        # Django core
        'django': {
            'handlers': ['file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'api_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['api_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['debug_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Custom apps
        'accounts': {
            'handlers': ['file', 'error_file', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'products': {
            'handlers': ['file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': ['payment_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'calendar_sync': {
            'handlers': ['file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'admissions': {
            'handlers': ['automation_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'sms': {
            'handlers': ['sms_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'email': {
            'handlers': ['email_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Celery
        'celery': {
            'handlers': ['celery_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['celery_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.worker': {
            'handlers': ['celery_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Automation scripts
        'automation': {
            'handlers': ['automation_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'scraper': {
            'handlers': ['automation_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # ===================================================================
        # CRITICAL: Silence third-party libraries that cause OSError
        # These libraries write to console by default, exceeding PythonAnywhere quota
        # ===================================================================
        # ===================================================================
        # CRITICAL: Silence ALL third-party libraries that cause OSError
        # These libraries write to console by default, exceeding PythonAnywhere quota
        # ===================================================================
        'httpx': {
            'handlers': ['null'],  # COMPLETELY SILENCE - causes most OSError issues
            'level': 'CRITICAL',  # Only log critical errors
            'propagate': False,
        },
        'httpcore': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'urllib3.connectionpool': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'requests': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        # Additional noisy libraries
        'chardet': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'charset_normalizer': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'PIL': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'cloudinary': {
            'handlers': ['api_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'parso': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'asyncio': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'concurrent': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'multipart': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'hpack': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'h2': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        # Expo/Push notification libraries
        'exponent_server_sdk': {
            'handlers': ['api_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'pywebpush': {
            'handlers': ['api_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        # Root logger catches everything not explicitly handled
        # CRITICAL: Use null handler first to prevent console output
        'handlers': ['file', 'error_file'],
        'level': 'WARNING',  # Reduced from INFO to reduce log volume
    },
}

# =============================================================================
# PERFORMANCE OPTIMIZATIONS FOR PYTHONANYWHERE
# =============================================================================

# Database connection pooling (reduce connection overhead)
CONN_MAX_AGE = 600  # Keep connections alive for 10 minutes

# Cache configuration for better performance
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Session optimization
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Disable verbose SQL logging in production
if not DEBUG:
    LOGGING['loggers']['django.db.backends']['level'] = 'ERROR'

# =============================================================================
# MEDIA STORAGE CONFIGURATION
# =============================================================================
# Configures the generic media storage system that supports multiple backends
# Available backends: 'cloudinary', 'local', 'google_drive', 's3'

# Primary storage backend (SWITCHED TO LOCAL - Cloudinary suspended)
# To switch back to Cloudinary, change default to 'cloudinary'
MEDIA_STORAGE_BACKEND = config('MEDIA_STORAGE_BACKEND', default='local')

# Fallback backends if primary fails (list of backend names)
MEDIA_STORAGE_FALLBACK = ['local']  # Local is now default, no fallback needed

# Model-specific storage backends (optional)
# This allows you to override the default storage backend for specific models
# Format: 'app_label.ModelName': 'backend_name'
# Example:
# MEDIA_MODEL_BACKENDS = {
#     'products.Product': 'google_drive',
#     'events.Event': 's3',
#     'news.Article': 'cloudinary',
# }
# Note: You can also set MEDIA_STORAGE_BACKEND directly on the model class
MEDIA_MODEL_BACKENDS = {}

# Local storage settings (for 'local' backend)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Site URL for generating full URLs (used by local storage backend)
# For local development: Leave empty to use relative URLs (works with Vite proxy)
# For production: https://your-domain.com
SITE_URL = config('SITE_URL', default='')

# Frontend URL for templates and redirects
# For local development: http://localhost:5173
# For production: https://biochemknust.com
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# Google Drive settings (for 'google_drive' backend) - Optional
# GOOGLE_DRIVE_CREDENTIALS = config('GOOGLE_DRIVE_CREDENTIALS_PATH', default='')
# GOOGLE_DRIVE_FOLDER_ID = config('GOOGLE_DRIVE_FOLDER_ID', default='')

# S3/Compatible settings (for 's3' backend) - Optional
# AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
# AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
# AWS_STORAGE_BUCKET_NAME = config('AWS_S3_BUCKET_NAME', default='')
# AWS_S3_REGION_NAME = config('AWS_S3_REGION', default='us-east-1')

# =============================================================================
# WEB PUSH NOTIFICATIONS (VAPID) CONFIGURATION
# =============================================================================
# Generate VAPID keys with: python manage.py generate_vapid_keys
# Keys are stored in DER format encoded as base64 (single line, no PEM headers)
WEBPUSH_SETTINGS = {
    'VAPID_PUBLIC_KEY': config('VAPID_PUBLIC_KEY', default=''),
    'VAPID_PRIVATE_KEY': config('VAPID_PRIVATE_KEY', default=''),
    'VAPID_ADMIN_EMAIL': config('VAPID_ADMIN_EMAIL', default=EMAIL_ADMIN),
}
